// Static Tailwind utility compositions. Keep class names complete for content scanning.
// Prefer utilities in JSX for new one-off styles; extract shared combinations here.
const styles = {
  heroBanner: [
    "relative",
    "isolate",
    "flex",
    "min-h-[max(700px,_100svh)]",
    "overflow-hidden",
    "p-0",
    "bg-[#173d2d]",
    "text-[#fff]",
    "max-[799.01px]:min-h-[max(700px,_100svh)]",
    "max-[380.01px]:min-h-[max(700px,_100svh)]",
  ].join(" "),
  heroPhotos: ["absolute", "inset-0", "z-[-2]", "bg-[#203d2f]"].join(" "),
  heroPhoto: [
    "absolute",
    "inset-0",
    "opacity-[0]",
    "[transition:opacity_0.65s_ease]",
    "[&[aria-hidden=false]]:opacity-[1]",
    "motion-reduce:transition-none",
  ].join(" "),
  heroShade: [
    "absolute",
    "inset-0",
    "z-[-1]",
    "bg-[linear-gradient(_90deg,_rgb(11_31_23_/_88%)_0%,_rgb(11_31_23_/_76%)_37%,_rgb(11_31_23_/_40%)_68%,_rgb(11_31_23_/_14%)_100%_),_linear-gradient(0deg,_rgb(11_31_23_/_45%),_transparent_50%),_linear-gradient(180deg,_rgb(11_31_23_/_65%),_transparent_42%)]",
  ].join(" "),
  heroPhotoImage: ["object-cover", "object-[center_52%]"].join(" "),
  heroContainer: [
    "relative",
    "flex",
    "[flex:0_1_auto]",
    "min-h-[inherit]",
    "items-center",
    "[padding-block:calc(var(--site-header-height)_+_56px)_144px]",
    "max-[799.01px]:items-start",
    "max-[799.01px]:[padding-block:calc(var(--site-header-height)_+_48px)_132px]",
    "max-[380.01px]:[padding-block:calc(var(--site-header-height)_+_36px)_120px]",
  ].join(" "),
  heroContent: [
    "w-[min(100%,_720px)]",
    "[&_>_.eyebrow]:mb-6",
    "[&_>_.eyebrow]:text-[#f0e8d1]",
    "[&_>_.eyebrow]:text-[0.72rem]",
    "[&_>_.eyebrow]:tracking-[0.12em]",
    "[&_h1]:max-w-[720px]",
    "[&_h1]:mb-0",
    "[&_h1]:text-[#fffdf8]",
    "[&_h1]:text-[clamp(3rem,_5.5vw,_5.25rem)]",
    "[&_h1]:font-medium",
    "[&_h1]:leading-[1.12]",
    "[&_h1]:tracking-[-0.055em]",
    "[&_h1]:text-balance",
    "[html[lang=bn]_&_h1]:leading-[1.4]",
    "[html[lang=bn]_&_h1]:tracking-normal",
    "max-[799.01px]:w-[min(100%,_640px)]",
    "max-[799.01px]:[&_>_.eyebrow]:mb-[22px]",
    "max-[799.01px]:[&_>_.eyebrow]:text-[0.65rem]",
    "max-[799.01px]:[&_>_.eyebrow]:leading-[1.6]",
    "max-[799.01px]:[&_h1]:text-[clamp(2.4rem,_7.8vw,_4rem)]",
    "max-[799.01px]:[&_h1]:leading-[1.12]",
    "max-[799.01px]:[html[lang=bn]_&_h1]:text-[clamp(2.2rem,_7.5vw,_3.7rem)]",
    "max-[799.01px]:[html[lang=bn]_&_h1]:leading-[1.38]",
    "max-[799.01px]:[html[lang=bn]_&_h1]:tracking-normal",
    "max-[380.01px]:[&_h1]:text-[2.3rem]",
    "max-[380.01px]:[html[lang=bn]_&_h1]:text-[2.15rem]",
  ].join(" "),
  heroStatusDot: [
    "w-[7px]",
    "h-[7px]",
    "[flex:0_0_7px]",
    "rounded-[50%]",
    "bg-[#e7c77d]",
  ].join(" "),
  heroSubhead: [
    "mt-5",
    "mx-0",
    "mb-0",
    "text-[#e7c77d]",
    "text-[clamp(1rem,_1.25vw,_1.2rem)]",
    "leading-[1.6]",
  ].join(" "),
  heroActions: [
    "grid",
    "justify-items-start",
    "gap-5",
    "mt-7",
    "[&_.actions]:gap-3",
    "max-[799.01px]:gap-4",
    "max-[799.01px]:mt-6",
    "max-[799.01px]:[&_.actions]:gap-2",
    "max-[380.01px]:[&_.actions]:flex-wrap",
  ].join(" "),
  photoChoices: [
    "flex",
    "flex-wrap",
    "gap-2",
    "[&_button]:inline-flex",
    "[&_button]:min-h-12",
    "[&_button]:items-center",
    "[&_button]:justify-center",
    "[&_button]:gap-[9px]",
    "[&_button]:border",
    "[&_button]:border-solid",
    "[&_button]:border-[rgb(255_253_248_/_48%)]",
    "[&_button]:rounded-[999px]",
    "[&_button]:py-2.5",
    "[&_button]:px-4",
    "[&_button]:bg-[rgb(20_43_31_/_44%)]",
    "[&_button]:text-[#fffdf8]",
    "[&_button]:text-[0.85rem]",
    "[&_button]:leading-[1.5]",
    "[&_button]:[transition:background-color_0.2s,_color_0.2s,_border-color_0.2s]",
    "[&_button]:[backdrop-filter:blur(10px)]",
    "[&_button:hover]:border-[#fffdf8]",
    "[&_button:hover]:bg-[rgb(255_253_248_/_14%)]",
    "[&_button[aria-current=true]]:border-[#f2dfb0]",
    "[&_button[aria-current=true]]:bg-[#f2dfb0]",
    "[&_button[aria-current=true]]:text-[#214533]",
    "[&_button[aria-current=true]]:shadow-[0_5px_20px_rgb(4_20_12_/_20%)]",
    "[&_button:focus-visible]:[outline:3px_solid_#f2dfb0]",
    "[&_button:focus-visible]:outline-offset-[4px]",
    "max-[799.01px]:gap-[7px]",
    "max-[799.01px]:[&_button]:min-h-[46px]",
    "max-[799.01px]:[&_button]:px-3",
    "max-[799.01px]:[&_button]:text-[0.8rem]",
    "max-[380.01px]:gap-1.5",
    "max-[380.01px]:[&_button]:gap-1.5",
    "max-[380.01px]:[&_button]:px-2.5",
    "max-[380.01px]:[&_button]:text-[0.74rem]",
    "max-[380.01px]:[&_button_svg]:w-[15px]",
  ].join(" "),
  heroThumbnail: [
    "[&:focus-visible]:[outline:3px_solid_#f2dfb0]",
    "[&:focus-visible]:outline-offset-[4px]",
    "relative",
    "flex",
    "w-[92px]",
    "h-[62px]",
    "items-end",
    "overflow-hidden",
    "border",
    "border-solid",
    "border-[rgb(255_253_248_/_50%)]",
    "rounded-[9px]",
    "p-0",
    "bg-[#294837]",
    "text-[#fffdf8]",
    "isolate",
    "[text-align:start]",
    "[&::after]:absolute",
    "[&::after]:z-[-1]",
    "[&::after]:inset-0",
    "[&::after]:bg-[linear-gradient(0deg,_rgb(11_31_23_/_85%),_transparent_90%)]",
    "[&::after]:content-['']",
    "[&_img]:z-[-2]",
    "[&_img]:object-cover",
    "[&_img]:[transition:transform_0.3s_ease]",
    "[&:hover_img]:[transform:scale(1.08)]",
    "[&[aria-current=true]_img]:[transform:scale(1.08)]",
    "[&[aria-current=true]]:[border:2px_solid_#f0d18f]",
    "[&[aria-current=true]]:shadow-[0_0_0_2px_rgb(24_45_33_/_45%)]",
    "[&_span]:z-[1]",
    "[&_span]:[display:-webkit-box]",
    "[&_span]:w-full",
    "[&_span]:overflow-hidden",
    "[&_span]:py-1",
    "[&_span]:px-1.5",
    "[&_span]:text-inherit",
    "[&_span]:text-[0.64rem]",
    "[&_span]:font-semibold",
    "[&_span]:leading-[1.4]",
    "[&_span]:[text-overflow:ellipsis]",
    "[&_span]:[-webkit-box-orient:vertical]",
    "[&_span]:[-webkit-line-clamp:1]",
    "max-[799.01px]:w-[min(92px,_22vw)]",
    "max-[799.01px]:h-[60px]",
  ].join(" "),
  carouselPlayback: [
    "[&:focus-visible]:[outline:3px_solid_#f2dfb0]",
    "[&:focus-visible]:outline-offset-[4px]",
    "grid",
    "place-items-center",
    "[flex:0_0_44px]",
    "w-11",
    "min-h-11",
    "border",
    "border-solid",
    "border-[rgb(255_253_248_/_55%)]",
    "rounded-[50%]",
    "bg-[rgb(15_39_28_/_54%)]",
    "text-[#fffdf8]",
    "[backdrop-filter:blur(10px)]",
    "[&:hover]:border-[#fffdf8]",
    "[&:hover]:bg-[rgb(255_253_248_/_18%)]",
  ].join(" "),
  carouselArrow: [
    "interactive-carouselArrow",
    "[&:focus-visible]:[outline:3px_solid_#f2dfb0]",
    "[&:focus-visible]:outline-offset-[4px]",
    "grid",
    "place-items-center",
    "[flex:0_0_44px]",
    "w-11",
    "min-h-11",
    "border",
    "border-solid",
    "border-[rgb(255_253_248_/_55%)]",
    "rounded-[50%]",
    "bg-[rgb(15_39_28_/_54%)]",
    "text-[#fffdf8]",
    "[backdrop-filter:blur(10px)]",
    "[&:hover]:border-[#fffdf8]",
    "[&:hover]:bg-[rgb(255_253_248_/_18%)]",
  ].join(" "),
  heroPrimaryAction: [
    "min-h-[50px]",
    "justify-center",
    "rounded-[999px]",
    "py-3",
    "px-[22px]",
    "text-[0.87rem]",
    "border",
    "border-solid",
    "border-[#f0d18f]",
    "bg-[#f0d18f]",
    "text-[#183d2d]",
    "[&:hover]:border-[#f8e7c1]",
    "[&:hover]:bg-[#f8e7c1]",
    "[&:hover]:text-[#183d2d]",
    "max-[799.01px]:min-h-12",
    "max-[799.01px]:px-4",
    "max-[799.01px]:text-[0.8rem]",
    "max-[380.01px]:px-[13px]",
    "max-[380.01px]:text-[0.74rem]",
  ].join(" "),
  heroSecondaryAction: [
    "min-h-[50px]",
    "justify-center",
    "rounded-[999px]",
    "py-3",
    "px-[22px]",
    "text-[0.87rem]",
    "border",
    "border-solid",
    "border-[rgb(255_253_248_/_60%)]",
    "bg-[rgb(20_43_31_/_36%)]",
    "text-[#fffdf8]",
    "[backdrop-filter:blur(8px)]",
    "[&:hover]:border-[#fffdf8]",
    "[&:hover]:bg-[rgb(255_253_248_/_14%)]",
    "[&:hover]:text-[#fffdf8]",
    "max-[799.01px]:min-h-12",
    "max-[799.01px]:px-4",
    "max-[799.01px]:text-[0.8rem]",
    "max-[380.01px]:px-[13px]",
    "max-[380.01px]:text-[0.74rem]",
  ].join(" "),
  heroCarousel: [
    "absolute",
    "right-0",
    "bottom-[34px]",
    "z-[2]",
    "flex",
    "items-center",
    "gap-3",
    "max-[799.01px]:right-0",
    "max-[799.01px]:bottom-[18px]",
    "max-[799.01px]:left-0",
    "max-[799.01px]:justify-center",
    "max-[799.01px]:gap-0",
    "max-[799.01px]:[&_>_.interactive-carouselArrow]:hidden",
  ].join(" "),
  heroCarouselControls: [
    "flex",
    "items-center",
    "gap-2.5",
    "max-[799.01px]:w-full",
    "max-[799.01px]:justify-center",
  ].join(" "),
  carouselPagination: [
    "flex",
    "items-center",
    "gap-2",
    "max-[799.01px]:w-[min(calc(100%_-_54px),_360px)]",
    "max-[799.01px]:justify-center",
    "max-[799.01px]:gap-2",
  ].join(" "),
  carouselCount: [
    "min-w-11",
    "text-[#fffdf8]",
    "text-[0.76rem]",
    "text-center",
    "[font-variant-numeric:tabular-nums]",
    "max-[799.01px]:hidden",
  ].join(" "),
  intentLabel: [
    "block",
    "text-[0.85rem]",
    "font-semibold",
    "mb-2.5",
    "leading-[1.6]",
  ].join(" "),
  inputLabel: [
    "block",
    "text-[0.85rem]",
    "font-semibold",
    "mb-2.5",
    "leading-[1.6]",
  ].join(" "),
  intentChoices: [
    "flex",
    "flex-wrap",
    "gap-1.5",
    "mb-5",
    "[&_button]:min-h-11",
    "[&_button]:border",
    "[&_button]:border-solid",
    "[&_button]:border-line",
    "[&_button]:rounded-[9px]",
    "[&_button]:py-2.5",
    "[&_button]:px-3",
    "[&_button]:bg-[#fff]",
    "[&_button]:text-ink",
    "[&_button]:inline-flex",
    "[&_button]:items-center",
    "[&_button]:justify-center",
    "[&_button]:gap-[7px]",
    "[&_button]:text-[0.8rem]",
    "[&_button]:leading-[1.6]",
    "[&_button]:[transition:background_0.2s,_border-color_0.2s]",
    "[&_button_svg]:shrink-0",
    "[&_button:hover]:border-[#6e8b67]",
    "[&_button[aria-pressed=true]]:bg-green",
    "[&_button[aria-pressed=true]]:text-[#fff]",
    "[&_button[aria-pressed=true]]:border-green",
    "[&_button[aria-pressed=true]]:shadow-[inset_0_-3px_0_#ffffff35]",
    "[&_button[aria-pressed=true]:focus-visible]:outline-offset-[3px]",
    "max-[1100.01px]:[&_button]:text-[0.75rem]",
    "max-[1100.01px]:[&_button]:px-2.5",
    "max-[380.01px]:[&_button]:grow",
  ].join(" "),
  demoTabs: [
    "flex",
    "flex-wrap",
    "gap-1.5",
    "[&_button]:min-h-11",
    "[&_button]:border",
    "[&_button]:border-solid",
    "[&_button]:border-line",
    "[&_button]:rounded-[9px]",
    "[&_button]:py-2.5",
    "[&_button]:px-3",
    "[&_button]:bg-[#fff]",
    "[&_button]:text-ink",
    "[&_button]:inline-flex",
    "[&_button]:items-center",
    "[&_button]:justify-center",
    "[&_button]:gap-[7px]",
    "[&_button]:text-[0.8rem]",
    "[&_button]:leading-[1.6]",
    "[&_button]:[transition:background_0.2s,_border-color_0.2s]",
    "[&_button_svg]:shrink-0",
    "[&_button:hover]:border-[#6e8b67]",
    "[&_button[aria-pressed=true]]:bg-green",
    "[&_button[aria-pressed=true]]:text-[#fff]",
    "[&_button[aria-pressed=true]]:border-green",
    "[&_button[aria-pressed=true]]:shadow-[inset_0_-3px_0_#ffffff35]",
    "[&_button[aria-pressed=true]:focus-visible]:outline-offset-[3px]",
    "max-[799.01px]:w-full",
    "max-[799.01px]:[&_button]:[flex:1]",
    "max-[380.01px]:[&_button]:px-2",
    "max-[380.01px]:[&_button]:gap-[5px]",
    "max-[380.01px]:[&_button]:text-[0.75rem]",
    "max-[380.01px]:[&_button_svg]:w-3.5",
  ].join(" "),
  periodChoices: [
    "flex",
    "flex-wrap",
    "gap-1.5",
    "[&_button]:min-h-11",
    "[&_button]:border",
    "[&_button]:border-solid",
    "[&_button]:border-line",
    "[&_button]:rounded-[9px]",
    "[&_button]:py-2.5",
    "[&_button]:px-3",
    "[&_button]:bg-[#fff]",
    "[&_button]:text-ink",
    "[&_button]:inline-flex",
    "[&_button]:items-center",
    "[&_button]:justify-center",
    "[&_button]:gap-[7px]",
    "[&_button]:text-[0.8rem]",
    "[&_button]:leading-[1.6]",
    "[&_button]:[transition:background_0.2s,_border-color_0.2s]",
    "[&_button:hover]:border-[#6e8b67]",
    "[&_button[aria-pressed=true]]:bg-green",
    "[&_button[aria-pressed=true]]:text-[#fff]",
    "[&_button[aria-pressed=true]]:border-green",
    "[&_button[aria-pressed=true]]:shadow-[inset_0_-3px_0_#ffffff35]",
  ].join(" "),
  intentResult: [
    "[&_p]:max-w-[470px]",
    "[&_p]:text-[0.93rem]",
    "[&_p]:min-h-[76px]",
    "[&_p]:mb-[22px]",
    "max-[799.01px]:[&_p]:min-h-0",
  ].join(" "),
  demoSection: [
    "pt-[76px]",
    "px-0",
    "pb-[90px]",
    "bg-[#f0f3eb]",
    "[border-top:1px_solid_#dfe5dc]",
    "[scroll-margin-top:24px]",
    "max-[799.01px]:py-12",
    "max-[799.01px]:px-0",
  ].join(" "),
  demoHeading: [
    "flex",
    "justify-between",
    "items-end",
    "gap-10",
    "mb-8",
    "[&_h2]:m-0",
    "[&_h2]:max-w-[640px]",
    "[&_>_p]:max-w-[340px]",
    "[&_>_p]:text-[0.9rem]",
    "[&_>_p]:m-0",
    "max-[1100.01px]:gap-6",
    "max-[799.01px]:block",
    "max-[799.01px]:[&_>_p]:max-w-[520px]",
    "max-[799.01px]:[&_>_p]:mt-5",
  ].join(" "),
  workspace: [
    "border",
    "border-solid",
    "border-[#d4ddcf]",
    "rounded-[22px]",
    "bg-[#fff]",
    "shadow-[0_24px_60px_#183f320a]",
    "overflow-hidden",
    "max-[799.01px]:rounded-[16px]",
  ].join(" "),
  workspaceTop: [
    "py-6",
    "px-[30px]",
    "flex",
    "items-center",
    "justify-between",
    "gap-5",
    "[border-bottom:1px_solid_#dfe5dc]",
    "[&_>_div]:flex",
    "[&_>_div]:items-center",
    "[&_>_div]:gap-3",
    "[&_strong]:block",
    "[&_strong]:text-[1rem]",
    "[&_div_div_>_span]:block",
    "[&_div_div_>_span]:text-[0.75rem]",
    "[&_div_div_>_span]:text-muted",
    "[&_div_div_>_span]:mt-[5px]",
    "[&_div_div_>_span]:leading-[1.6]",
    "max-[799.01px]:p-5",
    "max-[799.01px]:items-start",
    "max-[799.01px]:flex-wrap",
    "max-[799.01px]:gap-3.5",
  ].join(" "),
  badge: [
    "inline-flex",
    "items-center",
    "w-[fit-content]",
    "border",
    "border-solid",
    "border-[#d7e0cb]",
    "py-[5px]",
    "px-2.5",
    "bg-[#edf2e7]",
    "text-[#3b5635]",
    "rounded-[6px]",
    "text-[0.72rem]",
    "leading-[1.6]",
  ].join(" "),
  workspaceToolbar: [
    "flex",
    "justify-between",
    "items-center",
    "gap-4",
    "py-[18px]",
    "px-[30px]",
    "bg-[#fafbf8]",
    "[border-bottom:1px_solid_#dfe5dc]",
    "max-[1100.01px]:items-start",
    "max-[799.01px]:py-3.5",
    "max-[799.01px]:px-4",
    "max-[799.01px]:flex-wrap",
    "max-[799.01px]:gap-1",
  ].join(" "),
  reset: [
    "inline-flex",
    "items-center",
    "justify-center",
    "gap-2",
    "border-0",
    "border-none",
    "border-current",
    "py-2",
    "px-1",
    "min-h-11",
    "bg-transparent",
    "text-green",
    "text-[0.8rem]",
    "font-semibold",
    "leading-[1.6]",
    "[&_svg]:shrink-0",
    "[&:hover]:underline",
    "[&:hover]:underline-offset-[5px]",
    "max-[799.01px]:[margin-inline-start:auto]",
  ].join(" "),
  inlineButton: [
    "inline-flex",
    "items-center",
    "justify-center",
    "gap-2",
    "border-0",
    "border-none",
    "border-current",
    "py-2",
    "px-1",
    "min-h-11",
    "bg-transparent",
    "text-green",
    "text-[0.8rem]",
    "font-semibold",
    "leading-[1.6]",
    "[&_svg]:shrink-0",
    "[&:hover]:underline",
    "[&:hover]:underline-offset-[5px]",
  ].join(" "),
  demoPanel: [
    "p-8",
    "min-h-[420px]",
    "[&_h3]:text-[1.35rem]",
    "[&_h3]:leading-[1.5]",
    "[&_h3]:mb-3",
    "[&_h3]:tracking-[-0.02em]",
    "[&_p]:text-[0.87rem]",
    "max-[799.01px]:py-[22px]",
    "max-[799.01px]:px-[18px]",
    "max-[799.01px]:min-h-0",
  ].join(" "),
  animalView: [
    "grid",
    "grid-cols-[1fr_1.1fr]",
    "gap-10",
    "[&_>_*]:min-w-0",
    "max-[1100.01px]:gap-6",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:gap-6",
  ].join(" "),
  milkView: [
    "grid",
    "grid-cols-[1fr_1.1fr]",
    "gap-10",
    "[&_>_*]:min-w-0",
    "max-[1100.01px]:gap-6",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:gap-6",
  ].join(" "),
  financeHeading: [
    "[&_>_*]:min-w-0",
    "flex",
    "items-start",
    "justify-between",
    "gap-5",
    "[&_p]:max-w-[580px]",
    "[&_button]:shrink-0",
    "max-[799.01px]:block",
  ].join(" "),
  featureExplorer: [
    "[&_>_*]:min-w-0",
    "grid",
    "grid-cols-[0.9fr_1.1fr]",
    "gap-8",
    "pb-[60px]",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:gap-6",
    "max-[799.01px]:pb-9",
  ].join(" "),
  animalChoices: [
    "grid",
    "gap-3",
    "my-6",
    "mx-0",
    "[&_button]:flex",
    "[&_button]:items-center",
    "[&_button]:gap-3.5",
    "[&_button]:min-h-[84px]",
    "[&_button]:p-4",
    "[&_button]:bg-[#fafbf8]",
    "[&_button]:text-ink",
    "[&_button]:border",
    "[&_button]:border-solid",
    "[&_button]:border-line",
    "[&_button]:rounded-[12px]",
    "[&_button]:[text-align:start]",
    "[&_button[aria-pressed=true]]:[border:2px_solid_#214e3a]",
    "[&_button[aria-pressed=true]]:p-[15px]",
    "[&_button[aria-pressed=true]]:bg-[#edf2e8]",
    "[&_strong]:block",
    "[&_strong]:text-[1.05rem]",
    "[&_small]:block",
    "[&_small]:text-muted",
    "[&_small]:text-[0.8rem]",
    "[&_small]:mt-[5px]",
    "[&_button_>_svg]:[margin-inline-start:auto]",
    "[&_button_>_svg]:shrink-0",
    "max-[799.01px]:grid-cols-[1fr_1fr]",
    "max-[799.01px]:[&_button]:flex-wrap",
    "max-[799.01px]:[&_button]:p-3",
    "max-[799.01px]:[&_button]:gap-2.5",
    "max-[799.01px]:[&_button[aria-pressed=true]]:p-[11px]",
    "max-[799.01px]:[&_button_>_svg]:w-4",
    "max-[380.01px]:grid-cols-[1fr]",
  ].join(" "),
  animalAvatar: [
    "grid",
    "place-items-center",
    "rounded-[50%]",
    "bg-[#e2e9d8]",
    "h-[46px]",
    "w-[46px]",
    "shrink-0",
    "max-[799.01px]:h-9",
    "max-[799.01px]:w-9",
  ].join(" "),
  animalProfile: [
    "p-[26px]",
    "bg-[#f7f5ed]",
    "rounded-[16px]",
    "border",
    "border-solid",
    "border-[#e7e3d7]",
    "[&&_h3]:text-[2rem]",
    "[&&_h3]:mt-5",
    "[&&_h3]:mx-0",
    "[&&_h3]:mb-1",
    "[&_h4]:mt-5",
    "[&_h4]:mx-0",
    "[&_h4]:mb-3.5",
    "[&_h4]:text-[0.85rem]",
    "[&_h4]:font-semibold",
    "max-[799.01px]:p-[22px]",
  ].join(" "),
  profileData: [
    "m-0",
    "[&_>_div]:flex",
    "[&_>_div]:justify-between",
    "[&_>_div]:[align-items:baseline]",
    "[&_>_div]:gap-5",
    "[&_>_div]:py-3",
    "[&_>_div]:px-0",
    "[&_>_div]:[border-bottom:1px_solid_#dcded2]",
    "[&_>_div]:text-[0.85rem]",
    "[&_>_div]:leading-[1.6]",
    "[&_dt]:text-muted",
    "[&_dd]:m-0",
    "[&_dd]:[text-align:end]",
    "[&_dd]:font-semibold",
    "[&_dd]:[overflow-wrap:anywhere]",
  ].join(" "),
  recordPreview: [
    "[&_dl]:m-0",
    "[&_dl_>_div]:flex",
    "[&_dl_>_div]:justify-between",
    "[&_dl_>_div]:[align-items:baseline]",
    "[&_dl_>_div]:gap-5",
    "[&_dl_>_div]:py-3",
    "[&_dl_>_div]:px-0",
    "[&_dl_>_div]:[border-bottom:1px_solid_#dcded2]",
    "[&_dl_>_div]:text-[0.85rem]",
    "[&_dl_>_div]:leading-[1.6]",
    "[&_dt]:text-muted",
    "[&_dd]:m-0",
    "[&_dd]:[text-align:end]",
    "[&_dd]:font-semibold",
    "[&_dd]:[overflow-wrap:anywhere]",
    "mt-[30px]",
    "bg-[#fff]",
    "p-[26px]",
    "border",
    "border-solid",
    "border-line",
    "rounded-[15px]",
    "[&_h3]:mt-5",
    "[&_h3]:mx-0",
    "[&_h3]:mb-2.5",
    "[&_h3]:text-[1.15rem]",
    "[&_p]:mt-[18px]",
    "[&_p]:mx-0",
    "[&_p]:mb-0",
    "[&_p]:text-[0.75rem]",
    "max-[799.01px]:p-5",
  ].join(" "),
  expenseList: [
    "m-0",
    "max-w-[580px]",
    "[&_>_div]:flex",
    "[&_>_div]:justify-between",
    "[&_>_div]:[align-items:baseline]",
    "[&_>_div]:gap-5",
    "[&_>_div]:py-3",
    "[&_>_div]:px-0",
    "[&_>_div]:[border-bottom:1px_solid_#dcded2]",
    "[&_>_div]:text-[0.85rem]",
    "[&_>_div]:leading-[1.6]",
    "[&_dt]:text-muted",
    "[&_dd]:m-0",
    "[&_dd]:[text-align:end]",
    "[&_dd]:font-semibold",
    "[&_dd]:[overflow-wrap:anywhere]",
  ].join(" "),
  checkList: [
    "p-0",
    "my-5",
    "mx-0",
    "list-none",
    "grid",
    "gap-3",
    "[&_li]:flex",
    "[&_li]:items-start",
    "[&_li]:gap-[9px]",
    "[&_li]:text-[0.88rem]",
    "[&_li]:leading-[1.7]",
    "[&_svg]:shrink-0",
    "[&_svg]:mt-[3px]",
  ].join(" "),
  helper: [
    "!text-[0.8rem]",
    "leading-[1.8]",
    "mt-[18px]",
    "mx-0",
    "mb-0",
    "text-muted",
  ].join(" "),
  workspaceFoot: [
    "py-4",
    "px-[30px]",
    "[border-top:1px_solid_#dfe5dc]",
    "flex",
    "items-center",
    "justify-between",
    "gap-6",
    "bg-[#fafbf8]",
    "[&_p]:text-[0.75rem]",
    "[&_p]:m-0",
    "[&_p]:flex",
    "[&_p]:[align-items:baseline]",
    "[&_p]:gap-2",
    "[&_a]:shrink-0",
    "max-[799.01px]:py-4",
    "max-[799.01px]:px-5",
    "max-[799.01px]:flex-col",
    "max-[799.01px]:items-start",
    "max-[799.01px]:gap-2.5",
    "max-[799.01px]:[&_a]:[flex-shrink:1]",
  ].join(" "),
  plannerFields: [
    "grid",
    "grid-cols-[1fr_1fr]",
    "gap-4",
    "my-6",
    "mx-0",
    "[&_>_div]:min-w-0",
    "[&_input]:w-full",
    "[&_input]:min-w-0",
    "[&_input]:min-h-12",
    "[&_input]:[font-family:inherit]",
    "[&_input]:[font-size:inherit]",
    "[&_input]:[font-weight:inherit]",
    "[&_input]:[font-style:inherit]",
    "[&_input]:[font-variant:inherit]",
    "[&_input]:leading-[inherit]",
    "[&_input]:bg-white",
    "[&_input]:text-ink",
    "[&_input]:border",
    "[&_input]:border-solid",
    "[&_input]:border-[#abb9a4]",
    "[&_input]:rounded-[8px]",
    "[&_input]:py-3",
    "[&_input]:px-3.5",
    "[&_input[aria-invalid=true]]:border-[#a33327]",
    "[&_input[aria-invalid=true]]:bg-[#fff8f5]",
    "max-[799.01px]:grid-cols-[1fr]",
  ].join(" "),
  searchField: [
    "[&_input]:w-full",
    "[&_input]:min-w-0",
    "[&_input]:min-h-12",
    "[&_input]:[font-family:inherit]",
    "[&_input]:text-[0.85rem]",
    "[&_input]:[font-weight:inherit]",
    "[&_input]:[font-style:inherit]",
    "[&_input]:[font-variant:inherit]",
    "[&_input]:leading-[inherit]",
    "[&_input]:bg-white",
    "[&_input]:text-ink",
    "[&_input]:border",
    "[&_input]:border-solid",
    "[&_input]:border-[#abb9a4]",
    "[&_input]:rounded-[8px]",
    "[&_input]:py-3",
    "[&_input]:px-3.5",
    "[&_input]:pl-[42px]",
    "flex",
    "items-center",
    "relative",
    "[&_svg]:absolute",
    "[&_svg]:left-3.5",
    "[&_svg]:text-muted",
    "[&_svg]:pointer-events-none",
    "[&_input::placeholder]:text-[#697465]",
    "[&_input::placeholder]:opacity-[1]",
  ].join(" "),
  fieldError: [
    "text-[#9b3023]",
    "!text-[0.8rem]",
    "leading-[1.6]",
    "mt-2.5",
    "mx-0",
    "mb-0",
  ].join(" "),
  projection: [
    "p-[26px]",
    "rounded-[16px]",
    "bg-[#edf2e8]",
    "border",
    "border-solid",
    "border-[#dbe3d2]",
    "max-[799.01px]:p-[22px]",
    "max-[380.01px]:py-[18px]",
    "max-[380.01px]:px-3.5",
  ].join(" "),
  metrics: [
    "grid",
    "grid-cols-[1fr]",
    "gap-[18px]",
    "m-0",
    "[&_dt]:text-muted",
    "[&_dt]:text-[0.8rem]",
    "[&_dt]:leading-[1.6]",
    "[&_dt]:mb-2",
    "[&_dd]:m-0",
    "[&_dd]:text-[clamp(1.5rem,_2.5vw,_2rem)]",
    "[&_dd]:font-semibold",
    "[&_dd]:leading-[1.5]",
    "[&_dd]:[overflow-wrap:anywhere]",
    "[&_small]:text-[0.9rem]",
    "[&_small]:font-normal",
  ].join(" "),
  financeMetrics: [
    "[&_dt]:text-muted",
    "[&_dt]:text-[0.8rem]",
    "[&_dt]:leading-[1.6]",
    "[&_dt]:mb-2",
    "grid",
    "grid-cols-[repeat(3,1fr)]",
    "gap-4",
    "my-5",
    "mx-0",
    "[&_>_div]:min-w-0",
    "[&_>_div]:p-5",
    "[&_>_div]:border",
    "[&_>_div]:border-solid",
    "[&_>_div]:border-line",
    "[&_>_div]:rounded-[12px]",
    "[&_>_div]:bg-[#f6f8f1]",
    "[&_>_div:last-child]:bg-[#f6efdd]",
    "[&_>_div:last-child]:border-[#e8d8b6]",
    "[&_dd]:m-0",
    "[&_dd]:text-[clamp(1.2rem,_2.1vw,_1.8rem)]",
    "[&_dd]:font-semibold",
    "[&_dd]:[overflow-wrap:anywhere]",
    "[&_dd]:leading-[1.6]",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:[&_>_div]:p-[18px]",
    "max-[799.01px]:[&_dd]:text-[1.65rem]",
  ].join(" "),
  chart: [
    "mt-[26px]",
    "mx-0",
    "mb-0",
    "pt-5",
    "[border-top:1px_solid_#d2ddc7]",
    "[&_figcaption]:text-[0.8rem]",
    "[&_figcaption]:font-semibold",
    "[&_figcaption]:leading-[1.6]",
    "[&_figcaption_span]:block",
    "[&_figcaption_span]:text-muted",
    "[&_figcaption_span]:font-normal",
    "[&_figcaption_span]:text-[0.7rem]",
    "[&_figcaption_span]:mt-[3px]",
  ].join(" "),
  bars: [
    "flex",
    "items-end",
    "gap-2.5",
    "h-[162px]",
    "mt-2.5",
    "max-[380.01px]:gap-1.5",
  ].join(" "),
  barColumn: [
    "flex",
    "flex-col",
    "justify-end",
    "items-center",
    "[flex:1]",
    "min-w-0",
    "h-full",
    "[&_>_span]:text-[0.65rem]",
    "[&_>_span]:leading-[1.6]",
    "[&_>_span]:[overflow-wrap:anywhere]",
    "[&_>_span]:text-center",
    "[&_small]:text-[0.63rem]",
    "[&_small]:leading-[1.5]",
    "[&_small]:text-center",
  ].join(" "),
  bar: [
    "w-full",
    "max-w-[55px]",
    "mt-1.5",
    "mx-0",
    "mb-2",
    "rounded-[5px_5px_0_0]",
    "bg-[#5b7950]",
  ].join(" "),
  workflowSteps: [
    "list-none",
    "p-0",
    "grid",
    "gap-3",
    "mt-5",
    "mx-0",
    "mb-0",
    "[&_button]:w-full",
    "[&_button]:min-h-[100px]",
    "[&_button]:flex",
    "[&_button]:items-start",
    "[&_button]:gap-4",
    "[&_button]:border",
    "[&_button]:border-solid",
    "[&_button]:border-[#d7dfcf]",
    "[&_button]:rounded-[12px]",
    "[&_button]:p-5",
    "[&_button]:bg-[#fafbf7]",
    "[&_button]:text-ink",
    "[&_button]:[text-align:start]",
    "[&_button[aria-pressed=true]]:[border:2px_solid_#214e3a]",
    "[&_button[aria-pressed=true]]:p-[19px]",
    "[&_button[aria-pressed=true]]:bg-[#e5ecd9]",
    "[&_button_>_svg]:shrink-0",
    "[&_button_>_svg]:[margin-inline-start:auto]",
    "[&_button_>_svg]:mt-[7px]",
    "[&_strong]:block",
    "[&_strong]:text-[1rem]",
    "[&_strong]:leading-[1.6]",
    "[&_strong]:font-semibold",
    "max-[799.01px]:[&_button]:p-4",
    "max-[799.01px]:[&_button]:gap-3",
    "max-[799.01px]:[&_button[aria-pressed=true]]:p-[15px]",
  ].join(" "),
  stepBody: [
    "block",
    "text-muted",
    "text-[0.8rem]",
    "leading-[1.7]",
    "mt-2",
  ].join(" "),
  stepNumber: [
    "grid",
    "place-items-center",
    "w-8",
    "h-8",
    "shrink-0",
    "bg-[#fff]",
    "rounded-[50%]",
    "border",
    "border-solid",
    "border-[#cbd6c1]",
    "text-[0.7rem]",
  ].join(" "),
  emptyState: ["bg-[#eff3e9]", "rounded-[12px]", "p-6", "text-[0.9rem]"].join(
    " ",
  ),
  featureChoices: [
    "grid",
    "gap-3",
    "mt-5",
    "[&_button]:flex",
    "[&_button]:items-center",
    "[&_button]:gap-[18px]",
    "[&_button]:w-full",
    "[&_button]:min-h-[100px]",
    "[&_button]:p-[22px]",
    "[&_button]:border",
    "[&_button]:border-solid",
    "[&_button]:border-line",
    "[&_button]:rounded-[12px]",
    "[&_button]:bg-[#fff]",
    "[&_button]:text-ink",
    "[&_button]:[text-align:start]",
    "[&_button[aria-pressed=true]]:[border:2px_solid_#214e3a]",
    "[&_button[aria-pressed=true]]:p-[21px]",
    "[&_button[aria-pressed=true]]:bg-[#e9efdf]",
    "[&_button_>_span]:text-[0.75rem]",
    "[&_button_>_span]:shrink-0",
    "[&_strong]:font-medium",
    "[&_strong]:text-[1.1rem]",
    "[&_strong]:leading-[1.6]",
    "[&_svg]:[margin-inline-start:auto]",
    "[&_svg]:shrink-0",
    "max-[799.01px]:[&_button]:min-h-[76px]",
    "max-[799.01px]:[&_button]:p-[18px]",
    "max-[799.01px]:[&_button[aria-pressed=true]]:p-[17px]",
  ].join(" "),
  featureDetail: [
    "bg-[#f0f3e9]",
    "rounded-[18px]",
    "p-9",
    "border",
    "border-solid",
    "border-[#dce4d2]",
    "[&_h2]:text-[1.8rem]",
    "[&_p]:text-[0.95rem]",
    "max-[799.01px]:p-[26px]",
  ].join(" "),
  featureDetailTop: [
    "flex",
    "justify-between",
    "items-center",
    "gap-5",
    "mb-[30px]",
  ].join(" "),
  heroCarouselTrack: ["motion-reduce:transition-none"].join(" "),
  carouselDot: ["motion-reduce:[&::before]:transition-none"].join(" "),
} as const;

export default styles;
