// Static Tailwind utility compositions. Keep class names complete for content scanning.
// Prefer utilities in JSX for new one-off styles; extract shared combinations here.
const styles = {
  hero: [
    "pt-[70px]",
    "px-0",
    "pb-[76px]",
    "max-[799.01px]:pt-11",
    "max-[799.01px]:px-0",
    "max-[799.01px]:pb-12",
  ].join(" "),
  heroGrid: [
    "grid",
    "grid-cols-[1.05fr_1fr]",
    "gap-[60px]",
    "items-center",
    "[&_>_*]:min-w-0",
    "max-[1100.01px]:gap-[30px]",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:gap-9",
  ].join(" "),
  heroCopy: [
    "[&_h1]:text-[clamp(2.8rem,_4.7vw,_4.35rem)]",
    "[&_h1]:font-medium",
    "[&_h1]:leading-[1.08]",
    "[&_h1]:mb-6",
    "[&_h1]:tracking-[-0.065em]",
    "[&_h1_span]:text-[#67805a]",
    "[&_h1_span]:block",
    "[html[lang=bn]_&_h1]:leading-[1.4]",
    "[html[lang=bn]_&_h1]:tracking-normal",
    "[&_>_p]:max-w-[430px]",
    "[&_>_p]:text-[0.91rem]",
    "[&_>_p]:mb-7",
    "max-[1100.01px]:[&_h1]:text-[clamp(2.8rem,_4.9vw,_4rem)]",
    "max-[799.01px]:[&_h1]:text-[clamp(2.8rem,_8vw,_4.6rem)]",
    "max-[799.01px]:[&_>_p]:max-w-[540px]",
  ].join(" "),
  workflowGrid: [
    "[&_>_*]:min-w-0",
    "grid",
    "grid-cols-[1fr_1fr]",
    "gap-[90px]",
    "[&_>_div_>_p]:max-w-[380px]",
    "[&_>_div_>_p]:text-[0.87rem]",
    "max-[1100.01px]:gap-[45px]",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:gap-10",
  ].join(" "),
  faq: [
    "[&_>_*]:min-w-0",
    "grid",
    "grid-cols-[1fr_1.25fr]",
    "gap-[70px]",
    "pt-[30px]",
    "px-0",
    "pb-20",
    "[&_details]:[border-bottom:1px_solid_#dfe5dc]",
    "[&_details]:py-2",
    "[&_details]:px-0",
    "[&_summary]:flex",
    "[&_summary]:justify-between",
    "[&_summary]:gap-[18px]",
    "[&_summary]:items-center",
    "[&_summary]:cursor-pointer",
    "[&_summary]:list-none",
    "[&_summary]:text-[0.88rem]",
    "[&_summary]:min-h-[58px]",
    "[&_summary]:leading-[1.5]",
    "[&_summary::-webkit-details-marker]:hidden",
    "[&_summary_span]:text-[1.4rem]",
    "[&_summary_span]:font-normal",
    "[&_details[open]_summary_span]:[transform:rotate(45deg)]",
    "[&_details_p]:text-[0.83rem]",
    "[&_details_p]:leading-[1.8]",
    "[&_details_p]:pr-6",
    "[&_details_p]:mb-4",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:gap-3",
    "max-[799.01px]:pt-2.5",
    "max-[799.01px]:px-0",
    "max-[799.01px]:pb-12",
  ].join(" "),
  overviewHero: [
    "[html[lang=bn]_&_h1]:leading-[1.4]",
    "[html[lang=bn]_&_h1]:tracking-normal",
    "pt-20",
    "px-0",
    "pb-16",
    "max-w-[830px]",
    "[&_h1]:text-[clamp(2.8rem,_6vw,_4.9rem)]",
    "[&_h1]:font-medium",
    "[&_h1]:leading-[1.06]",
    "[&_h1]:tracking-[-0.065em]",
    "[&_>_p]:max-w-[620px]",
    "[&_>_p]:text-[1.08rem]",
    "max-[799.01px]:pt-12",
    "max-[799.01px]:px-0",
    "max-[799.01px]:pb-[30px]",
  ].join(" "),
  visualTop: [
    "[html[lang=bn]_&]:text-[0.72rem]",
    "[html[lang=bn]_&]:tracking-normal",
    "[html[lang=bn]_&]:leading-[1.6]",
    "absolute",
    "top-[46px]",
    "left-[54px]",
    "right-[54px]",
    "flex",
    "justify-between",
    "text-[0.48rem]",
    "tracking-[0.12em]",
    "text-[#466341]",
    "gap-2.5",
    "max-[1100.01px]:left-10",
    "max-[1100.01px]:right-10",
    "max-[799.01px]:top-16",
    "max-[799.01px]:text-[0.43rem]",
    "max-[799.01px]:left-[38px]",
    "max-[799.01px]:right-[38px]",
    "max-[380.01px]:left-[34px]",
    "max-[380.01px]:right-[34px]",
  ].join(" "),
  visualBottom: [
    "[html[lang=bn]_&]:text-[0.72rem]",
    "[html[lang=bn]_&]:tracking-normal",
    "[html[lang=bn]_&]:leading-[1.6]",
    "absolute",
    "bottom-0",
    "left-0",
    "right-0",
    "flex",
    "justify-between",
    "gap-3",
    "p-5",
    "bg-[#e6ecda]",
    "text-[0.49rem]",
    "tracking-[0.07em]",
    "text-[#3f5839]",
    "[&_>_span:first-child]:flex",
    "[&_>_span:first-child]:items-center",
    "[&_>_span:first-child]:gap-1.5",
    "max-[380.01px]:text-[0.42rem]",
    "max-[380.01px]:py-4",
    "max-[380.01px]:px-3",
  ].join(" "),
  noteCard: [
    "[html[lang=bn]_&_strong]:text-[0.9rem]",
    "[html[lang=bn]_&_strong]:leading-[1.6]",
    "[html[lang=bn]_&_small]:text-[0.75rem]",
    "[html[lang=bn]_&_small]:leading-[1.6]",
    "max-w-[calc(100%_-_28px)]",
    "absolute",
    "flex",
    "items-center",
    "gap-3",
    "bg-[#fffffff2]",
    "border",
    "border-solid",
    "border-[#fff]",
    "rounded-[10px]",
    "p-[15px]",
    "shadow-[0_12px_28px_#34472b12]",
    "[&_strong]:block",
    "[&_strong]:text-[0.74rem]",
    "[&_strong]:font-semibold",
    "[&_small]:block",
    "[&_small]:text-[0.59rem]",
    "[&_small]:text-[#59684f]",
    "[&_small]:mt-1.5",
    "max-[380.01px]:p-2.5",
    "max-[380.01px]:gap-2",
  ].join(" "),
  sectionHeading: [
    "[&_h2]:max-w-[650px]",
    "[&_h2]:mb-0",
    "[&_>_p]:max-w-[300px]",
    "[&_>_p]:shrink-0",
    "[&_>_p]:text-[0.85rem]",
    "[&_>_p]:mb-[5px]",
    "flex",
    "justify-between",
    "gap-[30px]",
    "items-end",
    "mb-[35px]",
    "max-[799.01px]:block",
    "max-[799.01px]:[&_>_p]:mt-[22px]",
  ].join(" "),
  heroNote: [
    "flex",
    "gap-[9px]",
    "items-center",
    "text-[0.68rem]",
    "text-muted",
    "mt-7",
  ].join(" "),
  visual: [
    "h-[520px]",
    "rounded-[180px_180px_20px_20px]",
    "bg-[#e3ead7]",
    "relative",
    "overflow-hidden",
    "border",
    "border-solid",
    "border-[#d8e1cc]",
    "max-[1100.01px]:h-[480px]",
    "max-[799.01px]:h-[460px]",
    "max-[799.01px]:max-w-[520px]",
    "max-[799.01px]:w-full",
    "max-[799.01px]:[justify-self:center]",
    "max-[380.01px]:h-[420px]",
  ].join(" "),
  sun: [
    "w-[120px]",
    "h-[120px]",
    "absolute",
    "top-[88px]",
    "right-[74px]",
    "bg-[#f4d890]",
    "rounded-[50%]",
    "shadow-[0_0_0_18px_#f4d89035]",
    "max-[380.01px]:right-[38px]",
  ].join(" "),
  fieldBack: [
    "absolute",
    "left-[-40%]",
    "right-[-30%]",
    "h-[320px]",
    "bottom-[-10px]",
    "bg-[#b6c89b]",
    "rounded-[50%_70%_0_0]",
    "[transform:rotate(-17deg)]",
  ].join(" "),
  fieldFront: [
    "absolute",
    "left-[-10%]",
    "right-[-50%]",
    "h-[300px]",
    "bottom-[-110px]",
    "bg-[#74915e]",
    "rounded-[60%_40%_0_0]",
    "[transform:rotate(18deg)]",
  ].join(" "),
  furrows: [
    "absolute",
    "inset-[330px_-80px_-70px_-70px]",
    "bg-[repeating-linear-gradient(_30deg,_transparent_0_26px,_#426d3e55_27px_29px,_transparent_30px_47px_)]",
    "[transform:rotate(-10deg)]",
    "rounded-[50%]",
  ].join(" "),
  barn: [
    "absolute",
    "w-[133px]",
    "h-[100px]",
    "bg-[#f5edd6]",
    "top-[246px]",
    "left-[44%]",
    "[transform:skewY(-6deg)]",
    "shadow-[20px_13px_0_#81956633]",
    "max-[380.01px]:top-[235px]",
  ].join(" "),
  roof: [
    "absolute",
    "left-[-12px]",
    "top-[-55px]",
    "w-[158px]",
    "h-[65px]",
    "bg-[#3d5841]",
    "[clip-path:polygon(50%_0,_100%_83%,_100%_100%,_0_100%,_0_83%)]",
  ].join(" "),
  barnDoor: [
    "absolute",
    "bottom-0",
    "left-12",
    "w-[38px]",
    "h-[62px]",
    "bg-[#7c8560]",
    "[border:5px_solid_#e6dcc2]",
    "[border-bottom:0]",
  ].join(" "),
  barnWindow: [
    "absolute",
    "top-[15px]",
    "left-3",
    "w-[22px]",
    "h-[22px]",
    "bg-[#b4be9d]",
    "[border:3px_solid_#e6dcc2]",
  ].join(" "),
  tree: [
    "absolute",
    "top-[188px]",
    "left-[19%]",
    "w-[65px]",
    "h-[143px]",
    "[&_span]:absolute",
    "[&_span]:w-[5px]",
    "[&_span]:h-[85px]",
    "[&_span]:bg-[#65704a]",
    "[&_span]:bottom-0",
    "[&_span]:left-[30px]",
    "[&_i]:block",
    "[&_i]:absolute",
    "[&_i]:top-0",
    "[&_i]:w-[65px]",
    "[&_i]:h-[100px]",
    "[&_i]:rounded-[70%_60%_55%_50%]",
    "[&_i]:bg-[#5e7c4e]",
    "[&_i]:shadow-[inset_-18px_-8px_0_#486c45]",
  ].join(" "),
  animalNote: [
    "top-[145px]",
    "left-[30px]",
    "max-[799.01px]:left-3.5",
    "max-[799.01px]:top-[135px]",
  ].join(" "),
  careNote: [
    "bottom-[92px]",
    "right-5",
    "max-[799.01px]:right-3",
    "max-[799.01px]:bottom-20",
    "max-[380.01px]:bottom-[60px]",
  ].join(" "),
  noteIcon: [
    "h-[38px]",
    "w-[38px]",
    "bg-[#eff2e5]",
    "rounded-[9px]",
    "grid",
    "place-items-center",
    "shrink-0",
  ].join(" "),
  check: [
    "grid",
    "place-items-center",
    "rounded-[50%]",
    "bg-[#e7eddc]",
    "w-[23px]",
    "h-[23px]",
    "ml-2.5",
    "max-[380.01px]:ml-0",
  ].join(" "),
  pillars: [
    "pt-[70px]",
    "px-0",
    "pb-20",
    "[border-top:1px_solid_#dfe5dc]",
    "max-[799.01px]:py-12",
    "max-[799.01px]:px-0",
  ].join(" "),
  pillarGrid: [
    "grid",
    "grid-cols-[repeat(3,1fr)]",
    "gap-[18px]",
    "max-[799.01px]:grid-cols-[1fr]",
  ].join(" "),
  pillarCard: [
    "flex",
    "flex-col",
    "rounded-[12px]",
    "p-[30px]",
    "min-w-0",
    "[transition:transform_0.2s]",
    "[&:hover]:[transform:translateY(-4px)]",
    "[&_h3]:text-[1.55rem]",
    "[&_h3]:mb-3.5",
    "[&_p]:text-[0.83rem]",
    "[&_p]:leading-[1.8]",
    "[&_p]:[flex:1]",
    "max-[1100.01px]:p-6",
    "max-[799.01px]:p-7",
    "max-[799.01px]:[&_p]:max-w-[500px]",
  ].join(" "),
  farmCard: ["bg-[#e9eee2]"].join(" "),
  learnCard: ["bg-[#f3ecdb]"].join(" "),
  vetCard: ["bg-[#e7eeea]"].join(" "),
  cardTop: [
    "flex",
    "justify-between",
    "items-center",
    "mb-10",
    "[&_span]:text-[0.65rem]",
    "[&_span]:text-[#5d7056]",
    "max-[799.01px]:mb-7",
  ].join(" "),
  cardLink: [
    "flex",
    "justify-between",
    "items-center",
    "[border-top:1px_solid_#63775430]",
    "pt-5",
    "mt-5",
    "text-[0.76rem]",
    "font-semibold",
    "min-h-11",
  ].join(" "),
  workflow: [
    "bg-[#f0f3eb]",
    "py-[78px]",
    "px-0",
    "[&_h2_span]:text-[#67805a]",
    "max-[799.01px]:py-12",
    "max-[799.01px]:px-0",
  ].join(" "),
  steps: [
    "p-0",
    "m-0",
    "list-none",
    "[&_li]:flex",
    "[&_li]:gap-5",
    "[&_li]:pt-0",
    "[&_li]:px-0",
    "[&_li]:pb-[26px]",
    "[&_li]:mb-[26px]",
    "[&_li]:[border-bottom:1px_solid_#dce3d5]",
    "[&_li:last-child]:m-0",
    "[&_li:last-child]:p-0",
    "[&_li:last-child]:border-0",
    "[&_li:last-child]:border-none",
    "[&_li:last-child]:border-current",
    "[&_li_>_span]:grid",
    "[&_li_>_span]:place-items-center",
    "[&_li_>_span]:shrink-0",
    "[&_li_>_span]:h-[34px]",
    "[&_li_>_span]:w-[34px]",
    "[&_li_>_span]:border",
    "[&_li_>_span]:border-solid",
    "[&_li_>_span]:border-[#cbd6c1]",
    "[&_li_>_span]:rounded-[50%]",
    "[&_li_>_span]:text-[0.66rem]",
    "[&_h3]:text-[1.08rem]",
    "[&_h3]:tracking-[-0.025em]",
    "[&_h3]:mt-[5px]",
    "[&_h3]:mx-0",
    "[&_h3]:mb-2",
    "[&_p]:text-[0.8rem]",
    "[&_p]:leading-[1.6]",
    "[&_p]:m-0",
  ].join(" "),
  editorialGrid: [
    "grid",
    "grid-cols-[1fr_1fr]",
    "py-20",
    "px-0",
    "gap-7",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:py-12",
    "max-[799.01px]:px-0",
    "max-[799.01px]:gap-5",
  ].join(" "),
  editorial: [
    "bg-[#eee9d9]",
    "rounded-[14px]",
    "p-[42px]",
    "[&_>_svg]:mb-8",
    "[&_.eyebrow]:mb-[15px]",
    "[&_h2]:text-[2.05rem]",
    "[&_p]:text-[0.86rem]",
    "[&_p]:max-w-[350px]",
    "max-[799.01px]:p-[30px]",
  ].join(" "),
  editorialCare: ["bg-[#e6ece3]"].join(" "),
  finalSection: ["pb-20", "max-[799.01px]:pb-12"].join(" "),
  finalCta: [
    "text-center",
    "bg-[#234c38]",
    "rounded-[18px]",
    "py-[62px]",
    "px-[30px]",
    "text-[#f5f6e9]",
    "relative",
    "overflow-hidden",
    "[&_.eyebrow]:justify-center",
    "[&_.eyebrow]:text-[#c4d2b4]",
    "[&_h2]:text-[clamp(2rem,_4vw,_3rem)]",
    "[&_h2]:mb-[15px]",
    "[&_p]:text-[#d0dcc6]",
    "[&_p]:text-[0.86rem]",
    "[&_p]:mb-7",
    "max-[799.01px]:py-11",
    "max-[799.01px]:px-6",
    "[&_a:focus-visible]:outline-[#f0f3e4]",
  ].join(" "),
  overviewGrid: [
    "grid",
    "grid-cols-[repeat(3,1fr)]",
    "gap-5",
    "pb-[65px]",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:pb-[35px]",
  ].join(" "),
  overviewCard: [
    "p-[30px]",
    "bg-[#edf1e7]",
    "rounded-[14px]",
    "[&_>_span]:text-[0.7rem]",
    "[&_>_span]:block",
    "[&_>_span]:mb-[35px]",
    "[&_>_span]:text-[#53654b]",
    "[&_h2]:text-[1.5rem]",
    "[&_p]:text-[0.87rem]",
    "max-[799.01px]:[&_>_span]:mb-[22px]",
  ].join(" "),
  availability: [
    "py-[26px]",
    "px-[30px]",
    "border",
    "border-solid",
    "border-line",
    "rounded-[12px]",
    "flex",
    "gap-5",
    "items-start",
    "mb-[65px]",
    "[&_svg]:shrink-0",
    "[&_svg]:mt-1",
    "[&_p]:text-[0.85rem]",
    "[&_p]:m-0",
    "max-[799.01px]:p-5",
    "max-[799.01px]:mb-[35px]",
  ].join(" "),
  overviewLinks: [
    "pb-[70px]",
    "flex",
    "gap-[25px]",
    "flex-wrap",
    "max-[799.01px]:pb-[45px]",
  ].join(" "),
} as const;

export default styles;
