// Static Tailwind utility compositions. Keep class names complete for content scanning.
// Prefer utilities in JSX for new one-off styles; extract shared combinations here.
const styles = {
  compactHero: [
    "pt-12",
    "px-0",
    "pb-[58px]",
    "[&_h1]:text-[clamp(2.4rem,_3.8vw,_3.55rem)]",
    "max-[1100.01px]:[&_h1]:text-[clamp(2.4rem,_3.8vw,_3.2rem)]",
    "max-[799.01px]:pt-[34px]",
    "max-[799.01px]:px-0",
    "max-[799.01px]:pb-[42px]",
    "max-[799.01px]:[&_h1]:text-[clamp(2.3rem,_8vw,_3.5rem)]",
  ].join(" "),
  previewWrap: [
    "min-w-0",
    "pt-[22px]",
    "pr-0",
    "pb-3",
    "pl-3",
    "relative",
    "isolate",
    "[&::before]:content-['']",
    "[&::before]:absolute",
    "[&::before]:inset-[0_-14px_0_0]",
    "[&::before]:rounded-[44px_14px_44px_14px]",
    "[&::before]:bg-[#e9edde]",
    "[&::before]:z-[-1]",
    "[&::before]:[transform:rotate(-2deg)]",
    "max-[799.01px]:py-3",
    "max-[799.01px]:px-0",
    "max-[799.01px]:max-w-[540px]",
    "max-[799.01px]:w-full",
    "max-[799.01px]:[justify-self:center]",
    "max-[799.01px]:[&::before]:inset-[0_-8px]",
  ].join(" "),
  demoAction: [
    "bg-transparent",
    "text-ink",
    "border",
    "border-solid",
    "border-[#91a17e]",
    "[&:hover]:bg-[#edf2e5]",
    "[&:hover]:text-ink",
  ].join(" "),
  productWindow: [
    "border",
    "border-solid",
    "border-[#cad5c3]",
    "rounded-[16px]",
    "bg-[#fffdf9]",
    "shadow-[0_18px_42px_#234c3812]",
    "overflow-hidden",
  ].join(" "),
  windowBar: [
    "flex",
    "gap-3",
    "items-center",
    "flex-wrap",
    "py-[15px]",
    "px-[18px]",
    "[border-bottom:1px_solid_#dfe5dc]",
    "bg-[#f4f6ef]",
    "text-[0.75rem]",
    "[&_strong]:mr-auto",
    "max-[1100.01px]:gap-2",
    "max-[380.01px]:p-[13px]",
    "max-[380.01px]:text-[0.7rem]",
  ].join(" "),
  windowDots: [
    "flex",
    "gap-1",
    "[&_i]:w-1.5",
    "[&_i]:h-1.5",
    "[&_i]:bg-[#94a587]",
    "[&_i]:rounded-[50%]",
    "max-[1100.01px]:hidden",
  ].join(" "),
  sampleBadge: [
    "inline-block",
    "py-[5px]",
    "px-[9px]",
    "border",
    "border-solid",
    "border-[#d5dfc9]",
    "rounded-[6px]",
    "bg-[#edf2e5]",
    "text-[#455e3b]",
    "text-[0.7rem]",
    "leading-[1.6]",
  ].join(" "),
  windowBody: [
    "p-6",
    "min-h-[352px]",
    "[&_h2]:text-[1.35rem]",
    "[&_h2]:tracking-[-0.03em]",
    "[&_h2]:mb-[18px]",
    "[&_h2]:leading-[1.5]",
    "max-[1100.01px]:p-5",
    "max-[799.01px]:min-h-[350px]",
    "max-[380.01px]:p-[18px]",
    "max-[380.01px]:[&_h2]:text-[1.2rem]",
  ].join(" "),
  previewHeading: [
    "flex",
    "gap-2",
    "items-center",
    "text-[0.75rem]",
    "text-muted",
    "mb-3.5",
    "[&_svg]:shrink-0",
  ].join(" "),
  animalRow: [
    "flex",
    "items-center",
    "gap-3",
    "mb-[18px]",
    "[&_strong]:text-[0.85rem]",
    "[&_small]:block",
    "[&_small]:mt-[3px]",
    "[&_small]:text-[0.7rem]",
    "[&_small]:text-muted",
  ].join(" "),
  animalAvatar: [
    "w-12",
    "h-12",
    "bg-[#eef1e5]",
    "rounded-[12px]",
    "grid",
    "place-items-center",
    "shrink-0",
    "[&_svg]:w-[42px]",
    "[&_svg]:h-[42px]",
  ].join(" "),
  previewMetrics: [
    "grid",
    "grid-cols-[1fr_1fr]",
    "gap-3",
    "mt-0",
    "mx-0",
    "mb-5",
    "[&_>_div]:py-[13px]",
    "[&_>_div]:px-3.5",
    "[&_>_div]:border",
    "[&_>_div]:border-solid",
    "[&_>_div]:border-line",
    "[&_>_div]:rounded-[10px]",
    "[&_dt]:text-[0.72rem]",
    "[&_dt]:text-muted",
    "[&_dt]:leading-[1.6]",
    "[&_dd]:mt-1",
    "[&_dd]:mx-0",
    "[&_dd]:mb-0",
    "[&_dd]:text-[1.75rem]",
    "[&_dd]:font-semibold",
    "[&_dd_small]:text-[0.8rem]",
    "[&_dd_small]:font-normal",
    "max-[380.01px]:gap-2",
    "max-[380.01px]:[&_>_div]:p-2.5",
  ].join(" "),
  miniChart: [
    "[&_>_div]:flex",
    "[&_>_div]:justify-between",
    "[&_>_div]:gap-2.5",
    "[&_>_div]:flex-wrap",
    "[&_>_div]:text-[0.7rem]",
    "[&_>_div]:mb-3",
    "[&_span]:text-muted",
    "[&_svg]:w-full",
    "[&_svg]:h-[82px]",
    "[&_svg]:block",
  ].join(" "),
  windowFoot: [
    "py-3.5",
    "px-[22px]",
    "bg-[#f0f3e9]",
    "text-[0.72rem]",
    "leading-[1.7]",
    "[border-top:1px_solid_#dfe5dc]",
  ].join(" "),
  previewCaption: [
    "flex",
    "flex-wrap",
    "gap-[6px_9px]",
    "items-center",
    "pt-[17px]",
    "px-3",
    "pb-0",
    "text-[0.75rem]",
    "[&_>_span:last-child]:[flex-basis:100%]",
    "[&_>_span:last-child]:pl-[26px]",
    "[&_>_span:last-child]:text-muted",
    "[&_>_span:last-child]:text-[0.7rem]",
  ].join(" "),
  previewSub: ["text-[0.8rem]"].join(" "),
  previewGuides: [
    "grid",
    "gap-2.5",
    "mt-[22px]",
    "[&_>_div]:flex",
    "[&_>_div]:items-center",
    "[&_>_div]:gap-3.5",
    "[&_>_div]:py-[17px]",
    "[&_>_div]:px-3.5",
    "[&_>_div]:border",
    "[&_>_div]:border-solid",
    "[&_>_div]:border-line",
    "[&_>_div]:rounded-[10px]",
    "[&_>_div]:text-[0.85rem]",
    "[&_span]:text-[0.7rem]",
    "[&_span]:text-muted",
    "[&_svg]:ml-auto",
    "[&_svg]:shrink-0",
  ].join(" "),
  previewHistory: [
    "my-[26px]",
    "mx-0",
    "[&_>_div]:flex",
    "[&_>_div]:items-center",
    "[&_>_div]:gap-3",
    "[&_>_div]:pb-6",
    "[&_>_div]:relative",
    "[&_>_div]:text-[0.85rem]",
    "[&_>_div:not(:last-child)::before]:content-['']",
    "[&_>_div:not(:last-child)::before]:absolute",
    "[&_>_div:not(:last-child)::before]:w-px",
    "[&_>_div:not(:last-child)::before]:bg-[#c9d6c0]",
    "[&_>_div:not(:last-child)::before]:top-[30px]",
    "[&_>_div:not(:last-child)::before]:bottom-0",
    "[&_>_div:not(:last-child)::before]:left-[15px]",
    "[&_>_div:last-child]:pb-0",
    "[&_span]:w-[30px]",
    "[&_span]:h-[30px]",
    "[&_span]:border",
    "[&_span]:border-solid",
    "[&_span]:border-[#c9d6c0]",
    "[&_span]:bg-[#f0f4e9]",
    "[&_span]:grid",
    "[&_span]:place-items-center",
    "[&_span]:rounded-[50%]",
    "[&_span]:shrink-0",
  ].join(" "),
  visualCard: [
    "!p-0",
    "border",
    "border-solid",
    "border-line",
    "overflow-hidden",
  ].join(" "),
  visualCardContent: [
    "p-[26px]",
    "flex",
    "flex-col",
    "[flex:1]",
    "[&_>_div:first-child]:mb-[22px]",
  ].join(" "),
  serviceArt: [
    "h-[172px]",
    "pt-3",
    "px-5",
    "pb-0",
    "[&_svg]:w-full",
    "[&_svg]:h-full",
    "[&_svg]:block",
  ].join(" "),
  art0: ["bg-[#e7edde]"].join(" "),
  art1: ["bg-[#f1e8d1]"].join(" "),
  art2: ["bg-[#e3ece5]"].join(" "),
  serviceCaption: [
    "text-[0.72rem]",
    "text-muted",
    "mb-3.5",
    "leading-[1.7]",
  ].join(" "),
  sectionHeading: [
    "flex",
    "gap-8",
    "items-end",
    "justify-between",
    "mb-[30px]",
    "[&_h2]:max-w-[640px]",
    "[&_h2]:mb-0",
    "[&_>_p]:max-w-[340px]",
    "[&_>_p]:text-[0.9rem]",
    "[&_>_p]:mb-0",
    "max-[799.01px]:block",
    "max-[799.01px]:[&_>_p]:mt-[18px]",
    "max-[799.01px]:[&_>_p]:max-w-[540px]",
  ].join(" "),
  speciesSection: ["pt-0", "px-0", "pb-[76px]", "max-[799.01px]:pb-12"].join(
    " ",
  ),
  speciesGrid: [
    "grid",
    "grid-cols-[1fr_1.15fr]",
    "gap-8",
    "items-stretch",
    "max-[799.01px]:grid-cols-[1fr]",
    "max-[799.01px]:gap-[18px]",
  ].join(" "),
  speciesChoices: [
    "grid",
    "grid-cols-[1fr_1fr]",
    "gap-3",
    "[&_button]:min-w-0",
    "[&_button]:min-h-[140px]",
    "[&_button]:relative",
    "[&_button]:bg-[#f1f4ea]",
    "[&_button]:border",
    "[&_button]:border-solid",
    "[&_button]:border-line",
    "[&_button]:rounded-[14px]",
    "[&_button]:flex",
    "[&_button]:flex-col",
    "[&_button]:items-center",
    "[&_button]:justify-center",
    "[&_button]:gap-1.5",
    "[&_button]:p-[18px]",
    "[&_button]:text-ink",
    "[&_button]:text-[0.9rem]",
    "[&_button]:font-semibold",
    "[&_button]:[transition:background_0.2s,_border-color_0.2s]",
    "[&_button_>_svg:first-child]:w-[66px]",
    "[&_button_>_svg:first-child]:h-[66px]",
    "[&_button_>_svg:last-child:not(:first-child)]:absolute",
    "[&_button_>_svg:last-child:not(:first-child)]:top-3",
    "[&_button_>_svg:last-child:not(:first-child)]:right-3",
    "[&_button:hover]:bg-[#e7eddf]",
    "[&_button:hover]:border-[#7d9672]",
    "[&_button[aria-pressed=true]]:[border:2px_solid_#214e3a]",
    "[&_button[aria-pressed=true]]:bg-[#e2ebd8]",
    "max-[799.01px]:grid-cols-[repeat(4,_minmax(0,_1fr))]",
    "max-[799.01px]:gap-2",
    "max-[799.01px]:[&_button]:min-h-[104px]",
    "max-[799.01px]:[&_button]:py-3",
    "max-[799.01px]:[&_button]:px-1.5",
    "max-[799.01px]:[&_button]:text-[0.8rem]",
    "max-[799.01px]:[&_button_>_svg:first-child]:w-[46px]",
    "max-[799.01px]:[&_button_>_svg:first-child]:h-[46px]",
    "max-[799.01px]:[&_button_>_svg:last-child:not(:first-child)]:top-[5px]",
    "max-[799.01px]:[&_button_>_svg:last-child:not(:first-child)]:right-[5px]",
    "max-[799.01px]:[&_button_>_svg:last-child:not(:first-child)]:w-3",
    "max-[380.01px]:grid-cols-2",
  ].join(" "),
  speciesDetail: [
    "min-w-0",
    "border",
    "border-solid",
    "border-line",
    "rounded-[14px]",
    "p-[30px]",
    "bg-[#fffdf9]",
    "[&_h3]:text-[1.55rem]",
    "[&_h3]:mt-[18px]",
    "[&_h3]:mx-0",
    "[&_h3]:mb-3",
    "[&_p]:text-[0.88rem]",
    "[&_ul]:list-none",
    "[&_ul]:p-0",
    "[&_ul]:my-5",
    "[&_ul]:mx-0",
    "[&_ul]:grid",
    "[&_ul]:gap-2.5",
    "[&_ul]:text-[0.84rem]",
    "[&_li]:flex",
    "[&_li]:gap-[9px]",
    "[&_li]:items-start",
    "[&_li]:leading-[1.7]",
    "[&_li_svg]:shrink-0",
    "[&_li_svg]:mt-[3px]",
    "[&_.text-link]:text-[0.85rem]",
    "max-[799.01px]:p-6",
  ].join(" "),
  resources: [
    "py-[68px]",
    "px-0",
    "[scroll-margin-top:24px]",
    "max-[799.01px]:py-12",
    "max-[799.01px]:px-0",
  ].join(" "),
  topicFilters: [
    "flex",
    "gap-2",
    "flex-wrap",
    "mt-[30px]",
    "mx-0",
    "mb-3",
    "[&_a]:inline-flex",
    "[&_a]:items-center",
    "[&_a]:justify-center",
    "[&_a]:min-h-11",
    "[&_a]:py-2.5",
    "[&_a]:px-4",
    "[&_a]:border",
    "[&_a]:border-solid",
    "[&_a]:border-line",
    "[&_a]:rounded-[24px]",
    "[&_a]:text-[0.85rem]",
    "[&_a:hover]:border-[#829675]",
    "[&_a[aria-current=true]]:bg-green",
    "[&_a[aria-current=true]]:text-[#fff]",
    "[&_a[aria-current=true]]:border-green",
  ].join(" "),
  catalogCount: ["text-[0.8rem]", "mb-[22px]"].join(" "),
  resourceGrid: [
    "grid",
    "grid-cols-[repeat(3,_minmax(0,_1fr))]",
    "gap-5",
    "max-[799.01px]:grid-cols-[1fr]",
  ].join(" "),
  resourceCard: [
    "min-w-0",
    "border",
    "border-solid",
    "border-line",
    "rounded-[14px]",
    "overflow-hidden",
    "flex",
    "flex-col",
    "bg-[#fffdf9]",
    "[transition:border-color_0.2s,_transform_0.2s]",
    "[&:hover]:[transform:translateY(-3px)]",
    "[&:hover]:border-[#8c9f7c]",
  ].join(" "),
  resourceArt: [
    "p-[26px]",
    "min-h-[120px]",
    "flex",
    "gap-5",
    "items-center",
    "[&_svg]:shrink-0",
    "[&_span]:text-[0.8rem]",
    "[&_span]:leading-[1.6]",
    "max-[799.01px]:min-h-[100px]",
    "max-[799.01px]:p-[22px]",
  ].join(" "),
  resourceContent: [
    "p-6",
    "flex",
    "flex-col",
    "[flex:1]",
    "[&_h3]:text-[1.3rem]",
    "[&_h3]:mb-3",
    "[&_h3]:leading-[1.5]",
    "[&_p]:text-[0.85rem]",
    "[&_p]:[flex:1]",
    "max-[799.01px]:p-6",
  ].join(" "),
  resourceMeta: [
    "flex",
    "flex-wrap",
    "gap-[7px_14px]",
    "text-[0.7rem]",
    "leading-[1.7]",
    "text-muted",
    "mb-[18px]",
  ].join(" "),
  resourceAction: [
    "flex",
    "justify-between",
    "gap-2.5",
    "items-center",
    "[border-top:1px_solid_#dfe5dc]",
    "pt-[18px]",
    "text-[0.8rem]",
    "font-semibold",
  ].join(" "),
  catalogMore: ["mt-7"].join(" "),
  catalogNote: [
    "text-[0.85rem]",
    "mt-[26px]",
    "mx-0",
    "mb-0",
    "max-w-[760px]",
  ].join(" "),
  article: [
    "max-w-[820px]",
    "pt-[50px]",
    "px-0",
    "pb-[70px]",
    "my-0",
    "mx-auto",
    "[&_>_.text-link]:mb-[34px]",
    "[&_h1]:text-[clamp(2rem,_4vw,_3.3rem)]",
    "[&_h1]:font-medium",
    "[&_h1]:leading-[1.3]",
    "[&_h1]:tracking-[-0.045em]",
    "[&_h1]:mb-6",
    "[&_section]:my-8",
    "[&_section]:mx-0",
    "[&_section_h2]:text-[1.5rem]",
    "[&_section_h2]:mb-3.5",
    "[&_section_p]:leading-[1.95]",
    "max-[799.01px]:pt-8",
    "max-[799.01px]:px-0",
    "max-[799.01px]:pb-12",
  ].join(" "),
  articleMeta: [
    "flex",
    "gap-3.5",
    "flex-wrap",
    "text-[0.8rem]",
    "text-muted",
    "mb-4",
  ].join(" "),
  articleIntro: ["text-[1.1rem]", "mb-10", "max-[799.01px]:text-[1rem]"].join(
    " ",
  ),
  takeaway: [
    "p-6",
    "bg-[#edf2e5]",
    "[border-left:3px_solid_#214e3a]",
    "rounded-[0_12px_12px_0]",
    "my-[34px]",
    "mx-0",
  ].join(" "),
  downloadBox: [
    "border",
    "border-solid",
    "border-line",
    "p-6",
    "rounded-[14px]",
    "my-[34px]",
    "mx-0",
    "[&_p]:text-[0.8rem]",
    "[&_p]:mt-3.5",
    "[&_p]:mx-0",
    "[&_p]:mb-0",
    "[&_a]:max-w-full",
    "[&_a]:text-center",
    "max-[799.01px]:p-5",
    "max-[380.01px]:[&_a]:text-[0.85rem]",
  ].join(" "),
  relatedGuides: [
    "[border-top:1px_solid_#dfe5dc]",
    "pt-[30px]",
    "mt-[38px]",
    "[&_h2]:text-[1.4rem]",
    "[&_a]:flex",
    "[&_a]:gap-3",
    "[&_a]:items-center",
    "[&_a]:justify-between",
    "[&_a]:min-h-[52px]",
    "[&_a]:py-3",
    "[&_a]:px-0",
    "[&_a]:[border-bottom:1px_solid_#dfe5dc]",
    "[&_a]:leading-[1.7]",
    "[&_svg]:shrink-0",
  ].join(" "),
} as const;

export default styles;
