// Static Tailwind utility compositions. Keep class names complete for content scanning.
// Prefer utilities in JSX for new one-off styles; extract shared combinations here.
const styles = {
  shell: [
    "w-11/12",
    "my-0",
    "mx-auto",
    "pt-[140px]",
    "pb-[72px]",
    "min-h-[80vh]",
    "max-[640.01px]:pt-[112px]",
    "max-[640.01px]:pb-12",
    "motion-reduce:[&_*]:scroll-auto",
  ].join(" "),
  navigation: [
    "flex",
    "gap-[12px_24px]",
    "flex-wrap",
    "text-[.9rem]",
    "mb-9",
    "[&_a]:underline",
    "[&_a]:underline-offset-[5px]",
    "max-[640.01px]:mb-7",
    "max-[640.01px]:text-[.85rem]",
  ].join(" "),
  heading: [
    "text-[clamp(2rem,_5vw,_3.4rem)]",
    "leading-[1.15]",
    "font-medium",
    "max-w-[850px]",
  ].join(" "),
  intro: ["max-w-[750px]", "mb-7"].join(" "),
  card: [
    "p-7",
    "border",
    "border-solid",
    "border-line",
    "rounded-[18px]",
    "bg-white",
    "mt-5",
    "[overflow-wrap:anywhere]",
    "[&_h2]:text-[1.5rem]",
    "[&_h2]:mt-0",
    "[&_h2]:mx-0",
    "[&_h2]:mb-4",
    "max-[640.01px]:py-5",
    "max-[640.01px]:px-4",
  ].join(" "),
  grid: [
    "workspace-grid",
    "grid",
    "grid-cols-2",
    "gap-[22px]",
    "max-[640.01px]:grid-cols-[minmax(0,1fr)]",
    "max-[640.01px]:gap-5",
  ].join(" "),
  field: [
    "grid",
    "gap-2",
    "content-start",
    "min-w-0",
    "[&_label]:text-[.95rem]",
    "[&_label]:font-semibold",
    "[&_input]:w-full",
    "[&_input]:border",
    "[&_input]:border-solid",
    "[&_input]:border-[#9aa99c]",
    "[&_input]:rounded-[9px]",
    "[&_input]:bg-[#fff]",
    "[&_input]:text-ink",
    "[&_input]:p-3",
    "[&_input]:[font-family:inherit]",
    "[&_input]:[font-size:inherit]",
    "[&_input]:[font-weight:inherit]",
    "[&_input]:[font-style:inherit]",
    "[&_input]:[font-variant:inherit]",
    "[&_input]:leading-[inherit]",
    "[&_input]:min-h-[46px]",
    "[&_select]:w-full",
    "[&_select]:border",
    "[&_select]:border-solid",
    "[&_select]:border-[#9aa99c]",
    "[&_select]:rounded-[9px]",
    "[&_select]:bg-[#fff]",
    "[&_select]:text-ink",
    "[&_select]:p-3",
    "[&_select]:[font-family:inherit]",
    "[&_select]:[font-size:inherit]",
    "[&_select]:[font-weight:inherit]",
    "[&_select]:[font-style:inherit]",
    "[&_select]:[font-variant:inherit]",
    "[&_select]:leading-[inherit]",
    "[&_select]:min-h-[46px]",
    "[&_textarea]:w-full",
    "[&_textarea]:border",
    "[&_textarea]:border-solid",
    "[&_textarea]:border-[#9aa99c]",
    "[&_textarea]:rounded-[9px]",
    "[&_textarea]:bg-[#fff]",
    "[&_textarea]:text-ink",
    "[&_textarea]:p-3",
    "[&_textarea]:[font-family:inherit]",
    "[&_textarea]:[font-size:inherit]",
    "[&_textarea]:[font-weight:inherit]",
    "[&_textarea]:[font-style:inherit]",
    "[&_textarea]:[font-variant:inherit]",
    "[&_textarea]:leading-[inherit]",
    "[&_textarea]:min-h-[46px]",
    "[&_textarea]:resize-y",
    "[&_small]:text-muted",
    "[&_small]:leading-[1.6]",
    "[&_input:focus-visible]:[outline:3px_solid_#a26913]",
    "[&_input:focus-visible]:outline-offset-[3px]",
    "[&_select:focus-visible]:[outline:3px_solid_#a26913]",
    "[&_select:focus-visible]:outline-offset-[3px]",
    "[&_textarea:focus-visible]:[outline:3px_solid_#a26913]",
    "[&_textarea:focus-visible]:outline-offset-[3px]",
    "[&_[aria-invalid=true]]:border-[#a33126]",
    "[&_.workspace-fieldError]:text-[#a33126]",
    "[&_.workspace-fieldError]:leading-[1.5]",
  ].join(" "),
  choices: [
    "[&_legend]:text-[.95rem]",
    "[&_legend]:font-semibold",
    "[&_legend]:py-0",
    "[&_legend]:px-[5px]",
    "[&:focus-visible]:[outline:3px_solid_#a26913]",
    "[&:focus-visible]:outline-offset-[3px]",
    "flex",
    "items-start",
    "flex-wrap",
    "gap-[14px_20px]",
    "border",
    "border-solid",
    "border-line",
    "rounded-[9px]",
    "p-4",
    "m-0",
    "min-w-0",
    "[&_label]:flex",
    "[&_label]:gap-[9px]",
    "[&_label]:items-start",
    "[&_label]:leading-[1.6]",
    "[&_input]:w-[18px]",
    "[&_input]:h-[18px]",
    "[&_input]:mt-[3px]",
    "[&_input]:shrink-0",
    "[&_input]:accent-green",
  ].join(" "),
  fieldError: ["workspace-fieldError", "text-[#a33126]", "leading-[1.5]"].join(
    " ",
  ),
  formFields: [
    "border-0",
    "border-none",
    "border-current",
    "m-0",
    "p-0",
    "min-w-0",
    "[&:disabled]:opacity-[.7]",
  ].join(" "),
  checkbox: [
    "flex",
    "gap-[9px]",
    "items-start",
    "leading-[1.6]",
    "[&_input]:w-[18px]",
    "[&_input]:h-[18px]",
    "[&_input]:mt-[3px]",
    "[&_input]:shrink-0",
    "[&_input]:accent-green",
  ].join(" "),
  full: ["col-span-full"].join(" "),
  actions: [
    "flex",
    "flex-wrap",
    "gap-3",
    "items-center",
    "mt-[26px]",
    "[&_>_.workspace-grid]:w-full",
    "max-[640.01px]:[&_>_*]:grow",
  ].join(" "),
  primary: [
    "inline-flex",
    "items-center",
    "justify-center",
    "py-3",
    "px-5",
    "rounded-[9px]",
    "[font-family:inherit]",
    "[font-size:inherit]",
    "[font-weight:inherit]",
    "[font-style:inherit]",
    "[font-variant:inherit]",
    "leading-[1.5]",
    "min-h-[46px]",
    "text-center",
    "border",
    "border-solid",
    "border-green",
    "bg-green",
    "text-[#fff]",
    "[&:disabled]:opacity-[.55]",
    "[&:disabled]:cursor-wait",
  ].join(" "),
  secondary: [
    "inline-flex",
    "items-center",
    "justify-center",
    "py-3",
    "px-5",
    "rounded-[9px]",
    "[font-family:inherit]",
    "[font-size:inherit]",
    "[font-weight:inherit]",
    "[font-style:inherit]",
    "[font-variant:inherit]",
    "leading-[1.5]",
    "min-h-[46px]",
    "text-center",
    "border",
    "border-solid",
    "border-[#9aa99c]",
    "text-ink",
    "bg-transparent",
    "[&:disabled]:opacity-[.55]",
    "[&:disabled]:cursor-wait",
  ].join(" "),
  notice: [
    "rounded-[10px]",
    "py-[15px]",
    "px-[18px]",
    "my-5",
    "mx-0",
    "leading-[1.7]",
    "[overflow-wrap:anywhere]",
    "text-[#214e3a]",
    "bg-[#edf3e9]",
    "border",
    "border-solid",
    "border-[#cbdcc6]",
  ].join(" "),
  error: [
    "rounded-[10px]",
    "py-[15px]",
    "px-[18px]",
    "my-5",
    "mx-0",
    "leading-[1.7]",
    "[overflow-wrap:anywhere]",
    "bg-[#fff0eb]",
    "text-[#87271f]",
    "border",
    "border-solid",
    "border-[#e7bcb3]",
  ].join(" "),
  details: [
    "m-0",
    "[&_div]:grid",
    "[&_div]:grid-cols-[minmax(130px,.65fr)_minmax(0,1fr)]",
    "[&_div]:gap-3",
    "[&_div]:py-3",
    "[&_div]:px-0",
    "[&_div]:[border-bottom:1px_solid_#dfe5dc]",
    "[&_dt]:font-semibold",
    "[&_dt]:text-[.9rem]",
    "[&_dd]:m-0",
    "[&_dd]:whitespace-pre-wrap",
    "[&_dd]:[overflow-wrap:anywhere]",
    "[&_dd]:leading-[1.6]",
    "max-[640.01px]:[&_div]:grid-cols-[minmax(0,1fr)]",
    "max-[640.01px]:[&_div]:gap-[7px]",
  ].join(" "),
  badge: [
    "inline-block",
    "py-1.5",
    "px-3",
    "bg-[#f5ecd8]",
    "text-[#604619]",
    "text-[.85rem]",
    "rounded-[20px]",
    "[&[data-state=APPROVED]]:bg-[#edf3e9]",
    "[&[data-state=APPROVED]]:text-[#214e3a]",
    "[&[data-state=REJECTED]]:bg-[#fff0eb]",
    "[&[data-state=REJECTED]]:text-[#87271f]",
  ].join(" "),
  list: [
    "grid",
    "gap-3.5",
    "p-0",
    "list-none",
    "[&_li]:[border-bottom:1px_solid_#dfe5dc]",
    "[&_li]:py-3",
    "[&_li]:px-0",
    "[&_li]:flex",
    "[&_li]:justify-between",
    "[&_li]:gap-5",
    "[&_li]:items-center",
    "[&_strong]:block",
    "[&_small]:block",
    "[&_small]:text-muted",
    "[&_small]:mt-[5px]",
    "max-[640.01px]:[&_li]:items-start",
    "max-[640.01px]:[&_li]:flex-col",
    "max-[640.01px]:[&_li]:gap-3",
  ].join(" "),
  confirmation: [
    "border",
    "border-solid",
    "border-line",
    "rounded-[18px]",
    "w-[min(540px,calc(100%_-_32px))]",
    "p-7",
    "max-h-[85dvh]",
    "overflow-y-auto",
    "text-ink",
    "[&::backdrop]:bg-[rgba(14,36,27,.55)]",
    "[&_h2]:text-[1.7rem]",
  ].join(" "),
} as const;

export default styles;
