// Static Tailwind utility compositions. Keep class names complete for content scanning.
// Prefer utilities in JSX for new one-off styles; extract shared combinations here.
const styles = {
  dialog: [
    "w-[min(480px,_calc(100%_-_32px))]",
    "max-h-[calc(100dvh_-_32px)]",
    "p-0",
    "border",
    "border-solid",
    "border-line",
    "rounded-[20px]",
    "bg-paper",
    "text-ink",
    "shadow-[0_24px_100px_#082f2860]",
    "overflow-y-auto",
    "overscroll-contain",
    "[&::backdrop]:bg-[#102d26b3]",
    "[&::backdrop]:[backdrop-filter:blur(4px)]",
    "[&_h2]:text-[1.9rem]",
    "[&_h2]:leading-[1.3]",
    "[&_h2]:mb-2.5",
    "[&_h2]:pr-2.5",
    "[&_button:disabled]:opacity-[0.6]",
    "[&_button:disabled]:cursor-wait",
    "max-[480.01px]:[&_h2]:text-[1.6rem]",
  ].join(" "),
  registerDialog: "w-[min(760px,_calc(100%_-_32px))]",
  content: [
    "relative",
    "p-8",
    "max-[480.01px]:py-[26px]",
    "max-[480.01px]:px-5",
  ].join(" "),
  close: [
    "absolute",
    "top-3",
    "right-3",
    "w-11",
    "h-11",
    "border-0",
    "border-none",
    "border-current",
    "rounded-[50%]",
    "bg-transparent",
    "text-ink",
    "grid",
    "place-items-center",
    "[&:hover]:bg-[#e8eee2]",
  ].join(" "),
  eyebrow: [
    "text-[0.7rem]",
    "font-bold",
    "tracking-[0.06em]",
    "text-muted",
    "mb-2",
  ].join(" "),
  description: ["text-[0.9rem]", "leading-[1.65]", "mb-6"].join(" "),
  formFields: [
    "border-0",
    "border-none",
    "border-current",
    "p-0",
    "m-0",
    "min-w-0",
  ].join(" "),
  field: [
    "mb-[17px]",
    "[&_label]:block",
    "[&_label]:text-[0.86rem]",
    "[&_label]:font-semibold",
    "[&_label]:leading-[1.5]",
    "[&_label]:mb-[7px]",
    "[&_input]:[font-family:inherit]",
    "[&_input]:[font-size:inherit]",
    "[&_input]:[font-weight:inherit]",
    "[&_input]:[font-style:inherit]",
    "[&_input]:[font-variant:inherit]",
    "[&_input]:leading-[inherit]",
    "[&_input]:w-full",
    "[&_input]:min-w-0",
    "[&_input]:h-12",
    "[&_input]:py-2.5",
    "[&_input]:px-3",
    "[&_input]:text-ink",
    "[&_input]:bg-white",
    "[&_input]:border",
    "[&_input]:border-solid",
    "[&_input]:border-[#a4b4a7]",
    "[&_input]:rounded-[7px]",
    "[&_input[aria-invalid=true]]:border-[#a73425]",
    "[&_select]:[font-family:inherit]",
    "[&_select]:[font-size:inherit]",
    "[&_select]:[font-weight:inherit]",
    "[&_select]:[font-style:inherit]",
    "[&_select]:[font-variant:inherit]",
    "[&_select]:leading-[inherit]",
    "[&_select]:w-full",
    "[&_select]:min-w-0",
    "[&_select]:h-12",
    "[&_select]:py-2.5",
    "[&_select]:px-3",
    "[&_select]:text-ink",
    "[&_select]:bg-white",
    "[&_select]:border",
    "[&_select]:border-solid",
    "[&_select]:border-[#a4b4a7]",
    "[&_select]:rounded-[7px]",
    "[&_select:focus-visible]:[outline:3px_solid_#a26913]",
    "[&_select:focus-visible]:outline-offset-[3px]",
    "[&_select[aria-invalid=true]]:border-[#a73425]",
  ].join(" "),
  registerFields: [
    "grid",
    "grid-cols-1",
    "gap-x-4",
    "gap-y-4",
    "min-[640px]:grid-cols-2",
    "[&_.auth-field]:mb-0",
    "mb-[22px]",
  ].join(" "),
  password: ["relative", "[&_input]:pr-[52px]"].join(" "),
  eye: [
    "absolute",
    "right-0.5",
    "top-0.5",
    "w-11",
    "h-11",
    "grid",
    "place-items-center",
    "bg-transparent",
    "text-muted",
    "border-0",
    "border-none",
    "border-current",
    "rounded-[5px]",
  ].join(" "),
  hint: [
    "block",
    "text-[0.78rem]",
    "leading-[1.65]",
    "mt-1.5",
    "text-muted",
  ].join(" "),
  fieldError: [
    "block",
    "text-[0.78rem]",
    "leading-[1.65]",
    "mt-1.5",
    "text-[#a12a1e]",
  ].join(" "),
  primary: [
    "w-full",
    "min-h-12",
    "flex",
    "justify-center",
    "items-center",
    "gap-3",
    "[font-family:inherit]",
    "text-[0.9rem]",
    "font-semibold",
    "[font-style:inherit]",
    "[font-variant:inherit]",
    "leading-[1.5]",
    "border-0",
    "border-none",
    "border-current",
    "rounded-[7px]",
    "p-3",
    "bg-green",
    "text-white",
    "[&:hover]:bg-[#123626]",
  ].join(" "),
  switch: [
    "[border-top:1px_solid_#dfe5dc]",
    "pt-4",
    "mt-5",
    "text-center",
    "text-[0.85rem]",
    "text-muted",
    "[&_button]:bg-transparent",
    "[&_button]:border-0",
    "[&_button]:border-none",
    "[&_button]:border-current",
    "[&_button]:text-ink",
    "[&_button]:[font-family:inherit]",
    "[&_button]:[font-size:inherit]",
    "[&_button]:font-semibold",
    "[&_button]:[font-style:inherit]",
    "[&_button]:[font-variant:inherit]",
    "[&_button]:leading-[inherit]",
    "[&_button]:min-h-11",
    "[&_button]:p-2",
    "[&_button]:underline",
    "[&_button]:underline-offset-[4px]",
  ].join(" "),
  inlineButton: [
    "bg-transparent",
    "border-0",
    "border-none",
    "border-current",
    "text-ink",
    "[font-family:inherit]",
    "[font-size:inherit]",
    "font-semibold",
    "[font-style:inherit]",
    "[font-variant:inherit]",
    "leading-[inherit]",
    "min-h-11",
    "p-2",
    "underline",
    "underline-offset-[4px]",
  ].join(" "),
  signOut: [
    "bg-transparent",
    "border-0",
    "border-none",
    "border-current",
    "text-ink",
    "[font-family:inherit]",
    "[font-size:inherit]",
    "font-semibold",
    "[font-style:inherit]",
    "[font-variant:inherit]",
    "leading-[inherit]",
    "min-h-11",
    "p-2",
    "underline",
    "underline-offset-[4px]",
    "block",
    "mt-2",
    "mx-auto",
    "mb-0",
  ].join(" "),
  error: [
    "block",
    "items-start",
    "gap-2.5",
    "py-3",
    "px-3.5",
    "mb-5",
    "rounded-[7px]",
    "text-[0.85rem]",
    "leading-[1.65]",
    "[overflow-wrap:anywhere]",
    "bg-[#fff0eb]",
    "border",
    "border-solid",
    "border-[#ecc8bb]",
    "text-[#822b21]",
  ].join(" "),
  success: [
    "flex",
    "items-start",
    "gap-2.5",
    "py-3",
    "px-3.5",
    "mb-5",
    "rounded-[7px]",
    "text-[0.85rem]",
    "leading-[1.65]",
    "[overflow-wrap:anywhere]",
    "bg-[#eaf2e5]",
    "text-[#214e3a]",
    "border",
    "border-solid",
    "border-[#b9ccae]",
    "[&_svg]:shrink-0",
    "[&_svg]:mt-0.5",
  ].join(" "),
  profile: [
    "[overflow-wrap:anywhere]",
    "p-5",
    "bg-white",
    "border",
    "border-solid",
    "border-line",
    "rounded-[12px]",
    "[&_strong]:block",
    "[&_strong]:text-[1.2rem]",
    "[&_dl]:my-4",
    "[&_dl]:mx-0",
    "[&_dl_div_+_div]:mt-3",
    "[&_dt]:text-[0.75rem]",
    "[&_dt]:text-muted",
    "[&_dt]:mb-[3px]",
    "[&_dd]:m-0",
    "[&_dd]:text-[0.9rem]",
    "[&_dd]:leading-[1.5]",
  ].join(" "),
  accountLinks: [
    "grid",
    "gap-2.5",
    "my-5",
    "mx-0",
    "[&_a]:underline",
    "[&_a]:underline-offset-[4px]",
  ].join(" "),
  sessionNote: ["text-[0.8rem]", "leading-[1.65]", "my-[18px]", "mx-0"].join(
    " ",
  ),
  controls: [
    "flex",
    "items-center",
    "gap-2",
    "[&_button:disabled]:cursor-wait",
    "[&_button:disabled]:opacity-[0.65]",
    "max-[1150.01px]:[&_.auth-headerSignUp]:hidden",
    "max-[799.01px]:hidden",
  ].join(" "),
  mobileControls: [
    "flex",
    "items-center",
    "gap-2",
    "pt-3",
    "px-0",
    "pb-1",
    "[border-top:1px_solid_#dfe5dc]",
    "mt-3",
    "justify-between",
    "[&_.auth-headerSignIn]:text-ink",
  ].join(" "),
  headerSignIn: [
    "auth-headerSignIn",
    "[font-family:inherit]",
    "text-[0.85rem]",
    "font-semibold",
    "[font-style:inherit]",
    "[font-variant:inherit]",
    "leading-[inherit]",
    "inline-flex",
    "items-center",
    "justify-center",
    "gap-1.5",
    "min-h-11",
    "py-2",
    "px-2.5",
    "whitespace-nowrap",
    "rounded-[7px]",
    "cursor-pointer",
    "bg-transparent",
    "border-0",
    "border-none",
    "border-current",
    "text-inherit",
  ].join(" "),
  headerSignUp: [
    "auth-headerSignUp",
    "[font-family:inherit]",
    "text-[0.85rem]",
    "font-semibold",
    "[font-style:inherit]",
    "[font-variant:inherit]",
    "leading-[inherit]",
    "inline-flex",
    "items-center",
    "justify-center",
    "gap-1.5",
    "min-h-11",
    "py-2",
    "px-2.5",
    "whitespace-nowrap",
    "rounded-[7px]",
    "cursor-pointer",
    "bg-green",
    "text-white",
    "border",
    "border-solid",
    "border-transparent",
  ].join(" "),
  spinner: ["animate-spin", "motion-reduce:animate-none"].join(" "),
  srOnly: [
    "absolute",
    "w-px",
    "h-px",
    "overflow-hidden",
    "[clip-path:inset(50%)]",
    "whitespace-nowrap",
  ].join(" "),
} as const;

export default styles;
