// Static Tailwind utility compositions. Keep class names complete for content scanning.
// Prefer utilities in JSX for new one-off styles; extract shared combinations here.
const styles = {
  document: [
    "[--site-header-height:94px]",
    "[scroll-padding-top:calc(var(--site-header-height)_+_20px)]",
    "[:where(&)_main]:[scroll-margin-top:calc(var(--site-header-height)_+_20px)]",
    "[:where(&)_*]:box-border",
    "[:where(&)_a]:text-inherit",
    "[:where(&)_a]:no-underline",
    "[:where(&)_a]:[-webkit-tap-highlight-color:transparent]",
    "[:where(&)_button]:[font-family:inherit]",
    "[:where(&)_button]:[font-size:inherit]",
    "[:where(&)_button]:[font-weight:inherit]",
    "[:where(&)_button]:[font-style:inherit]",
    "[:where(&)_button]:[font-variant:inherit]",
    "[:where(&)_button]:leading-[inherit]",
    "[:where(&)_button]:[-webkit-tap-highlight-color:transparent]",
    "[:where(&)_button]:cursor-pointer",
    "[:where(&)_summary]:[-webkit-tap-highlight-color:transparent]",
    "[:where(&)_a:focus-visible]:[outline:3px_solid_#a26913]",
    "[:where(&)_a:focus-visible]:outline-offset-[5px]",
    "[:where(&)_button:focus-visible]:[outline:3px_solid_#a26913]",
    "[:where(&)_button:focus-visible]:outline-offset-[5px]",
    "[:where(&)_input:focus-visible]:[outline:3px_solid_#a26913]",
    "[:where(&)_input:focus-visible]:outline-offset-[5px]",
    "[:where(&)_summary:focus-visible]:[outline:3px_solid_#a26913]",
    "[:where(&)_summary:focus-visible]:outline-offset-[5px]",
    "[:where(&)_h1]:mt-0",
    "[:where(&)_h1]:tracking-[-0.045em]",
    "[:where(&)_h2]:mt-0",
    "[:where(&)_h2]:tracking-[-0.045em]",
    "[:where(&)_h2]:text-[clamp(2rem,_3.4vw,_3rem)]",
    "[:where(&)_h2]:leading-[1.15]",
    "[:where(&)_h2]:font-medium",
    "[:where(&)_h2]:mb-6",
    "[:where(&)_h3]:mt-0",
    "[:where(&)_h3]:tracking-[-0.045em]",
    "[:where(&)_h3]:text-[1.35rem]",
    "[:where(&)_h3]:font-medium",
    "[:where(&)_p]:mt-0",
    "[:where(&)_p]:text-[1rem]",
    "[:where(&)_p]:leading-[1.75]",
    "[:where(&)_p]:text-muted",
    "[:where(&)[lang=bn]_body]:font-bengali",
    "[:where(&)[lang=bn]_h1]:tracking-normal",
    "[:where(&)[lang=bn]_h1]:leading-[1.45]",
    "[:where(&)[lang=bn]_h2]:tracking-normal",
    "[:where(&)[lang=bn]_h2]:leading-[1.45]",
    "[:where(&)[lang=bn]_h3]:tracking-normal",
    "[:where(&)[lang=bn]_h3]:leading-[1.45]",
    "[:where(&)_#mobile-menu]:absolute",
    "[:where(&)_#mobile-menu]:top-full",
    "[:where(&)_#mobile-menu]:left-0",
    "[:where(&)_#mobile-menu]:right-0",
    "[:where(&)_#mobile-menu]:bg-[#fff]",
    "[:where(&)_#mobile-menu]:text-ink",
    "[:where(&)_#mobile-menu]:py-4",
    "[:where(&)_#mobile-menu]:px-6",
    "[:where(&)_#mobile-menu]:shadow-[0_12px_18px_#183f3210]",
    "[:where(&)_#mobile-menu]:[border-bottom:1px_solid_#dfe5dc]",
    "[:where(&)_#mobile-menu_a]:flex",
    "[:where(&)_#mobile-menu_a]:items-center",
    "[:where(&)_#mobile-menu_a]:min-h-12",
    "max-[799.01px]:[--site-header-height:76px]",
    "motion-reduce:[:where(&)_*]:!scroll-auto",
    "motion-reduce:[:where(&)_*]:!transition-none",
    "motion-reduce:[:where(&)_*]:!animate-none",
    "motion-reduce:[:where(&)_*::before]:!scroll-auto",
    "motion-reduce:[:where(&)_*::before]:!transition-none",
    "motion-reduce:[:where(&)_*::before]:!animate-none",
    "motion-reduce:[:where(&)_*::after]:!scroll-auto",
    "motion-reduce:[:where(&)_*::after]:!transition-none",
    "motion-reduce:[:where(&)_*::after]:!animate-none",
  ].join(" "),
  body: ["m-0", "bg-paper", "text-ink", "font-sans", "antialiased"].join(" "),
  container: ["container", "w-11/12", "mx-auto"].join(" "),
  eyebrow: [
    "eyebrow",
    "text-[0.65rem]",
    "tracking-[0.16em]",
    "font-bold",
    "leading-[1.7]",
    "flex",
    "items-center",
    "gap-[9px]",
    "mb-6",
    "[html[lang=bn]_&]:tracking-normal",
    "[html[lang=bn]_&]:leading-[1.45]",
    "[html[lang=bn]_&]:text-[0.85rem]",
    "max-[799.01px]:text-[0.6rem]",
  ].join(" "),
  "status-dot": [
    "status-dot",
    "w-1.5",
    "h-1.5",
    "rounded-[100%]",
    "bg-[#668347]",
    "inline-block",
    "shrink-0",
  ].join(" "),
  "site-header": [
    "site-header",
    "border-x-0 border-t-0 border-b border-solid border-line",
    "bg-[#fff]",
    "sticky",
    "top-0",
    "z-[20]",
    "[transition:background-color_0.2s,_color_0.2s,_box-shadow_0.2s,_border-color_0.2s]",
    "[&.is-scrolled]:bg-[#fff]",
    "[&.is-scrolled]:text-ink",
    "[&.is-scrolled]:border-line",
    "[&.is-scrolled]:shadow-[0_5px_22px_#183f3210]",
  ].join(" "),
  "site-header--overlay": [
    "site-header--overlay",
    "fixed",
    "[inset-inline:0]",
    "text-[#fffdf8]",
    "bg-transparent",
    "border-transparent",
    "[&:not(.is-scrolled)_.header-cta]:bg-transparent",
    "[&:not(.is-scrolled)_.header-cta]:text-inherit",
    "[&:not(.is-scrolled)_.header-cta:hover]:underline",
    "[&:not(.is-scrolled)_.header-cta:hover]:underline-offset-[6px]",
    "[&:not(.is-scrolled)_.language-switcher]:border-[#ffffff66]",
    "[&:not(.is-scrolled)_.language-switcher]:text-inherit",
    "[&:not(.is-scrolled)_.menu-toggle]:border-[#ffffff66]",
    "[&:not(.is-scrolled)_.menu-toggle]:text-inherit",
    "[&:not(.is-scrolled)_.language-switcher_button]:bg-transparent",
    "[&:not(.is-scrolled)_.language-switcher_button]:text-inherit",
    "[&:not(.is-scrolled)_.language-switcher_button[aria-pressed=true]]:shadow-[inset_0_-2px_0_#eac474]",
    "[&:not(.is-scrolled)_a:focus-visible]:outline-amber",
    "[&:not(.is-scrolled)_button:focus-visible]:outline-amber",
    "[&:not(.is-scrolled)_#mobile-menu_a:focus-visible]:outline-[#a26913]",
  ].join(" "),
  "header-inner": [
    "header-inner",
    "h-[var(--site-header-height)]",
    "flex",
    "items-center",
    "justify-between",
    "gap-6",
    "max-[1000.01px]:gap-4",
    "max-[799.01px]:gap-2",
  ].join(" "),
  "language-switcher": [
    "language-switcher",
    "flex",
    "shrink-0",
    "p-0.5",
    "border",
    "border-solid",
    "border-line",
    "rounded-[7px]",
    "[&_button]:min-h-11",
    "[&_button]:min-w-11",
    "[&_button]:border-0",
    "[&_button]:border-none",
    "[&_button]:border-current",
    "[&_button]:rounded-[5px]",
    "[&_button]:py-1",
    "[&_button]:px-[6px]",
    "[&_button]:bg-transparent",
    "[&_button]:text-ink",
    "[&_button]:text-[0.8rem]",
    "[&_button]:leading-[1.6]",
    "[&_button[aria-pressed=true]]:bg-green",
    "[&_button[aria-pressed=true]]:text-white",
    "max-[799.01px]:[&_button]:px-1.5",
    "max-[799.01px]:[&_button]:text-[0.75rem]",
  ].join(" "),
  "desktop-nav": [
    "desktop-nav",
    "[html[lang=bn]_&]:text-[0.95rem]",
    "flex",
    "gap-[30px]",
    "items-center",
    "text-[0.8rem]",
    "font-medium",
    "[&_a]:flex",
    "[&_a]:min-h-11",
    "[&_a]:items-center",
    "[&_a:hover]:underline",
    "[&_a:hover]:underline-offset-[6px]",
    "max-[1000.01px]:gap-5",
    "max-[799.01px]:hidden",
  ].join(" "),
  button: [
    "button",
    "[html[lang=bn]_&]:text-[0.95rem]",
    "inline-flex",
    "justify-center",
    "items-center",
    "gap-5",
    "min-h-[52px]",
    "py-3.5",
    "px-[22px]",
    "bg-green",
    "text-white",
    "rounded-[7px]",
    "text-[0.8rem]",
    "font-semibold",
    "leading-[1.5]",
    "[transition:background_0.2s]",
    "[&:hover]:bg-[#123626]",
  ].join(" "),
  "text-link": [
    "text-link",
    "[html[lang=bn]_&]:text-[0.95rem]",
    "[&:hover]:underline",
    "[&:hover]:underline-offset-[6px]",
    "inline-flex",
    "min-h-11",
    "gap-3.5",
    "items-center",
    "text-[0.83rem]",
    "font-semibold",
  ].join(" "),
  "footer-top": [
    "footer-top",
    "[html[lang=bn]_&_nav_a]:text-[0.95rem]",
    "flex",
    "justify-between",
    "gap-10",
    "pb-11",
    "[&_p]:text-[0.83rem]",
    "[&_p]:mt-5",
    "[&_nav]:grid",
    "[&_nav]:gap-1",
    "[&_nav]:min-w-[210px]",
    "[&_nav_a]:flex",
    "[&_nav_a]:justify-between",
    "[&_nav_a]:items-center",
    "[&_nav_a]:gap-5",
    "[&_nav_a]:min-h-11",
    "[&_nav_a]:text-[0.85rem]",
    "[&_nav_a:hover]:underline",
    "max-[799.01px]:flex-col",
    "max-[799.01px]:[&_nav]:max-w-[340px]",
  ].join(" "),
  "button-small": [
    "button-small",
    "min-h-11",
    "py-3",
    "px-[17px]",
    "text-[0.73rem]",
  ].join(" "),
  "button-light": [
    "button-light",
    "bg-[#f0f3e4]",
    "text-ink",
    "[&:hover]:bg-white",
  ].join(" "),
  actions: [
    "actions",
    "flex",
    "items-center",
    "flex-wrap",
    "gap-6",
    "max-[799.01px]:gap-3.5",
  ].join(" "),
  "mobile-navigation": [
    "mobile-navigation",
    "hidden",
    "max-[799.01px]:block",
  ].join(" "),
  "menu-toggle": [
    "menu-toggle",
    "w-11",
    "h-11",
    "grid",
    "place-items-center",
    "[background:none]",
    "border",
    "border-solid",
    "border-line",
    "rounded-[7px]",
    "text-ink",
  ].join(" "),
  "skip-link": [
    "skip-link",
    "absolute",
    "left-4",
    "top-[-100px]",
    "bg-ink",
    "text-white",
    "p-[15px]",
    "z-[30]",
    "[&:focus]:top-2.5",
  ].join(" "),
  "site-footer": [
    "site-footer",
    "bg-[#eff2eb]",
    "[border-top:1px_solid_#dfe5dc]",
    "pt-[50px]",
    "px-0",
    "pb-5",
  ].join(" "),
  "footer-bottom": [
    "footer-bottom",
    "[border-top:1px_solid_#d4ddcf]",
    "pt-[22px]",
    "flex",
    "justify-between",
    "gap-5",
    "text-muted",
    "text-[0.7rem]",
    "leading-[1.6]",
    "max-[799.01px]:flex-col",
    "max-[799.01px]:gap-2",
  ].join(" "),
  "not-found": [
    "not-found",
    "min-h-[55vh]",
    "py-20",
    "[&_h1]:text-[clamp(3rem,_7vw,_5rem)]",
    "[&_h1]:font-medium",
    "[&_p]:max-w-[500px]",
  ].join(" "),
  "header-cta": ["header-cta", "max-[1000.01px]:hidden"].join(" "),
} as const;

export default styles;
