export enum HealthEscalationLevel {
  LEVEL_1_STAFF_ALERT = "LEVEL_1_STAFF_ALERT",
  LEVEL_2_OWNER_ALERT = "LEVEL_2_OWNER_ALERT",
  LEVEL_3_EMERGENCY_INTERVENTION = "LEVEL_3_EMERGENCY_INTERVENTION",
}
