import {
  AnimalSpecies,
  SpeciesVaccineProtocolDto,
  VaccineRecordType,
} from "@vetralink/shared-types";

export const SPECIES_VACCINE_PROTOCOLS: Record<
  AnimalSpecies,
  SpeciesVaccineProtocolDto
> = {
  [AnimalSpecies.COW]: {
    species: AnimalSpecies.COW,
    speciesDisplayName: "Cattle (Bovine)",
    description:
      "Standard preventative immunization and parasite control protocol for commercial dairy and beef cattle.",
    steps: [
      {
        name: "Foot and Mouth Disease (FMD) Quadrivalent",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Foot and Mouth Disease (Aphthovirus)",
        defaultFrequencyDays: 180,
        timingDescription: "Biannual (every 6 months), prior to monsoon/wet season",
        mandatory: true,
        recommendedDose: "2.0 - 3.0 ml",
        route: "Deep Intramuscular or Subcutaneous",
      },
      {
        name: "Anthrax Spore Vaccine",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Bacillus anthracis",
        defaultFrequencyDays: 365,
        timingDescription: "Annual booster, recommended pre-monsoon",
        mandatory: true,
        recommendedDose: "1.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Blackleg Vaccine",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Clostridium chauvoei",
        defaultFrequencyDays: 365,
        timingDescription: "Annual booster in calves and young stock under 2 years",
        mandatory: true,
        recommendedDose: "2.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Hemorrhagic Septicemia (HS)",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Pasteurella multocida",
        defaultFrequencyDays: 365,
        timingDescription: "Annual booster before rainy season",
        mandatory: true,
        recommendedDose: "2.0 - 3.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Strategic Broad-Spectrum Deworming",
        recordType: VaccineRecordType.DEWORMING,
        targetDisease: "Gastrointestinal Nematodes, Flukes, Tapeworms",
        defaultFrequencyDays: 90,
        timingDescription: "Quarterly (every 3 months) or seasonal pasture turnover",
        mandatory: true,
        recommendedDose: "Albendazole (10 mg/kg) or Ivermectin (0.2 mg/kg)",
        route: "Oral Drench or Subcutaneous",
      },
    ],
  },
  [AnimalSpecies.BUFFALO]: {
    species: AnimalSpecies.BUFFALO,
    speciesDisplayName: "Water Buffalo (Bubaline)",
    description:
      "Preventative health and anthelmintic schedule optimized for water buffalo operations.",
    steps: [
      {
        name: "Foot and Mouth Disease (FMD)",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Foot and Mouth Disease (Aphthovirus)",
        defaultFrequencyDays: 180,
        timingDescription: "Biannual (every 6 months)",
        mandatory: true,
        recommendedDose: "3.0 ml",
        route: "Deep Intramuscular",
      },
      {
        name: "Hemorrhagic Septicemia (HS)",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Pasteurella multocida",
        defaultFrequencyDays: 365,
        timingDescription: "Annual booster, critical for water-loving buffalo",
        mandatory: true,
        recommendedDose: "3.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Anthrax Vaccine",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Bacillus anthracis",
        defaultFrequencyDays: 365,
        timingDescription: "Annual, pre-monsoon",
        mandatory: true,
        recommendedDose: "1.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Liver Fluke & Nematode Deworming",
        recordType: VaccineRecordType.DEWORMING,
        targetDisease: "Fasciola gigantica & GI Nematodes",
        defaultFrequencyDays: 90,
        timingDescription: "Quarterly rotation (Triclabendazole/Oxyclozanide)",
        mandatory: true,
        recommendedDose: "Triclabendazole 12 mg/kg",
        route: "Oral Drench",
      },
    ],
  },
  [AnimalSpecies.GOAT]: {
    species: AnimalSpecies.GOAT,
    speciesDisplayName: "Goat (Caprine)",
    description:
      "Specialized immunization and barber pole worm anthelmintic management for meat and dairy goats.",
    steps: [
      {
        name: "PPR (Peste des Petits Ruminants) Vaccine",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Peste des Petits Ruminants Virus",
        defaultFrequencyDays: 365,
        timingDescription: "Annual booster (or triennial depending on local strain)",
        mandatory: true,
        recommendedDose: "1.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Enterotoxemia (Pulpy Kidney)",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Clostridium perfringens Type D",
        defaultFrequencyDays: 180,
        timingDescription: "Biannual (every 6 months), crucial for high-concentrate diets",
        mandatory: true,
        recommendedDose: "2.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Goat Pox Vaccine",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Capripoxvirus",
        defaultFrequencyDays: 365,
        timingDescription: "Annual booster",
        mandatory: false,
        recommendedDose: "0.5 ml",
        route: "Subcutaneous",
      },
      {
        name: "Targeted Anthelmintic Deworming",
        recordType: VaccineRecordType.DEWORMING,
        targetDisease: "Haemonchus contortus & Trichostrongyles",
        defaultFrequencyDays: 90,
        timingDescription: "Quarterly or based on FAMACHA anemia scoring",
        mandatory: true,
        recommendedDose: "Fenbendazole (10 mg/kg) or Levamisole (7.5 mg/kg)",
        route: "Oral Drench",
      },
    ],
  },
  [AnimalSpecies.SHEEP]: {
    species: AnimalSpecies.SHEEP,
    speciesDisplayName: "Sheep (Ovine)",
    description:
      "Flock health vaccination and anthelmintic schedule for commercial sheep herds.",
    steps: [
      {
        name: "PPR (Peste des Petits Ruminants)",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "PPR Virus",
        defaultFrequencyDays: 365,
        timingDescription: "Annual vaccination",
        mandatory: true,
        recommendedDose: "1.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Enterotoxemia & Tetanus (CD&T)",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Clostridium perfringens types C & D + Clostridium tetani",
        defaultFrequencyDays: 180,
        timingDescription: "Biannual, with booster 4-6 weeks prior to lambing",
        mandatory: true,
        recommendedDose: "2.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Sheep Pox",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Capripoxvirus",
        defaultFrequencyDays: 365,
        timingDescription: "Annual booster",
        mandatory: false,
        recommendedDose: "0.5 ml",
        route: "Subcutaneous",
      },
      {
        name: "Strategic Anthelmintic Deworming",
        recordType: VaccineRecordType.DEWORMING,
        targetDisease: "Nematodes, Tapeworms & Liver Flukes",
        defaultFrequencyDays: 90,
        timingDescription: "Quarterly rotational treatment",
        mandatory: true,
        recommendedDose: "Ivermectin or Closantel",
        route: "Oral Drench / SC",
      },
    ],
  },
  [AnimalSpecies.CAMEL]: {
    species: AnimalSpecies.CAMEL,
    speciesDisplayName: "Camel (Camelus dromedarius)",
    description:
      "Preventative health schedule tailored to arid pastoralist and dairy camel herds.",
    steps: [
      {
        name: "Camel Pox Vaccine",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Orthopoxvirus cameli",
        defaultFrequencyDays: 365,
        timingDescription: "Annual vaccination before breeding season",
        mandatory: true,
        recommendedDose: "1.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Hemorrhagic Septicemia",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Pasteurella multocida",
        defaultFrequencyDays: 365,
        timingDescription: "Annual vaccination",
        mandatory: true,
        recommendedDose: "2.0 ml",
        route: "Subcutaneous",
      },
      {
        name: "Trypanosomiasis & Gastrointestinal Deworming",
        recordType: VaccineRecordType.DEWORMING,
        targetDisease: "Trypanosoma evansi & GI Parasites",
        defaultFrequencyDays: 180,
        timingDescription: "Biannual treatment",
        mandatory: true,
        recommendedDose: "Ivermectin 0.2 mg/kg",
        route: "Subcutaneous",
      },
    ],
  },
  [AnimalSpecies.POULTRY]: {
    species: AnimalSpecies.POULTRY,
    speciesDisplayName: "Poultry (Chickens, Ducks, Turkeys)",
    description:
      "Flock-level preventative schedule for commercial layer and broiler poultry operations.",
    steps: [
      {
        name: "Newcastle Disease (ND / Ranikhet - Lasota)",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Avian Paramyxovirus type 1",
        defaultFrequencyDays: 60,
        timingDescription: "Primary day 7 & 21; booster every 60-90 days in layers",
        mandatory: true,
        recommendedDose: "1 drop in eye or via cool skim milk water",
        route: "Ocular / Oral (Drinking water)",
      },
      {
        name: "Infectious Bursal Disease (Gumboro - IBD)",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Birnavirus (Gumboro)",
        defaultFrequencyDays: 90,
        timingDescription: "Administered at day 14 and day 28",
        mandatory: true,
        recommendedDose: "Mass oral application",
        route: "Drinking water",
      },
      {
        name: "Fowl Pox",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Avipoxvirus",
        defaultFrequencyDays: 180,
        timingDescription: "Administered at week 6-8 of age",
        mandatory: false,
        recommendedDose: "Standard stab dose",
        route: "Wing-web puncture",
      },
      {
        name: "Flock Anthelmintic Deworming",
        recordType: VaccineRecordType.DEWORMING,
        targetDisease: "Ascaridia galli & Heterakis gallinarum",
        defaultFrequencyDays: 60,
        timingDescription: "Every 6-8 weeks in floor-reared and free-range flocks",
        mandatory: true,
        recommendedDose: "Piperazine or Levamisole water soluble",
        route: "Drinking water",
      },
    ],
  },
  [AnimalSpecies.OTHER]: {
    species: AnimalSpecies.OTHER,
    speciesDisplayName: "Other Livestock",
    description: "General baseline guidelines for other domestic species.",
    steps: [
      {
        name: "Rabies Inactivated Vaccine",
        recordType: VaccineRecordType.VACCINATION,
        targetDisease: "Rabies Lyssavirus",
        defaultFrequencyDays: 365,
        timingDescription: "Annual booster",
        mandatory: true,
        recommendedDose: "1.0 ml",
        route: "Subcutaneous or Intramuscular",
      },
      {
        name: "Broad-Spectrum Deworming",
        recordType: VaccineRecordType.DEWORMING,
        targetDisease: "Nematodes & Cestodes",
        defaultFrequencyDays: 180,
        timingDescription: "Biannual administration",
        mandatory: true,
        recommendedDose: "Veterinary prescription",
        route: "Oral / Injectable",
      },
    ],
  },
};
